Repository jaegertracing/jaeger, pull requests merged in 2023-11, with the labels that each got.

#4915 Fix release script broken by recent linting cleanup
  scripts/package-deploy.sh
Labels: changelog:ci

#4890 ci: Test jaeger-v2 as all-in-one in CI
  .github/workflows/ci-all-in-one-build.yml
  cmd/jaeger-v2/Dockerfile
  cmd/jaeger-v2/internal/extension/jaegerquery/server.go
  go.mod
  go.sum
  scripts/build-all-in-one-image.sh
Labels: v2, changelog:ci

#4918 exp: Rename jaeger-v2 binary to just jaeger
  .github/workflows/ci-all-in-one-build.yml
  Makefile
  cmd/jaeger-v2/.gitignore
  cmd/jaeger/.gitignore
  cmd/jaeger/Dockerfile
  cmd/jaeger/README.md
  cmd/jaeger/config-ui.json
  cmd/jaeger/config.yaml
  cmd/jaeger/internal/.nocover
  cmd/jaeger/internal/all-in-one.yaml
  cmd/jaeger/internal/all-in-one/.nocover
  cmd/jaeger/internal/all-in-one/config.go
  cmd/jaeger/internal/command.go
  cmd/jaeger/internal/components.go
  cmd/jaeger/internal/exporters/storageexporter/.nocover
  cmd/jaeger/internal/exporters/storageexporter/README.md
  cmd/jaeger/internal/exporters/storageexporter/config.go
  cmd/jaeger/internal/exporters/storageexporter/exporter.go
  cmd/jaeger/internal/exporters/storageexporter/factory.go
  cmd/jaeger/internal/extension/jaegerquery/.nocover
  cmd/jaeger/internal/extension/jaegerquery/README.md
  cmd/jaeger/internal/extension/jaegerquery/config.go
  cmd/jaeger/internal/extension/jaegerquery/factory.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerstorage/.nocover
  cmd/jaeger/internal/extension/jaegerstorage/README.md
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/extension/jaegerstorage/factory.go
  cmd/jaeger/main.go
  cmd/query/app/flags.go
  plugin/storage/memory/factory.go
  scripts/build-all-in-one-image.sh
Labels: changelog:exprimental

#4919 exp: Publish jaeger v2 image
  scripts/build-all-in-one-image.sh
Labels: changelog:ci

#4920 ci: Build jaeger v2 image on main branch runs
  .github/workflows/ci-all-in-one-build.yml
Labels: changelog:ci

#4912 Updates on self-assesment, security-insights, and security.md file or passing CLOMonitor checks
  SECURITY-INSIGHTS.yml
  SECURITY.md
  SELF-ASSESMENT.md
Labels: changelog:skip

#4922 Fix typo in SECURITY-INSIGHTS.yml
  SECURITY-INSIGHTS.yml
Labels: changelog:skip

#4933 Split unit-test workflow into tests and lint
  .github/workflows/ci-lint-checks.yaml
  .github/workflows/ci-unit-tests.yml
Labels: changelog:ci

#4913 Make ArchiveTrace button auto-configurable
  cmd/query/app/fixture/index.html
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
  cmd/query/app/server.go
  cmd/query/app/static_handler.go
  cmd/query/app/static_handler_test.go
Labels: changelog:new-feature

#4932 Read OTEL env vars for resource attributes
  pkg/jtracer/jtracer.go
Labels: changelog:bugfix-or-minor-feature

#4917 Remove google.golang.org/protobuf dependency from model & storage APIs
  Makefile
  model/proto/model_test.proto
  model/prototest/model_test.pb.go
  plugin/storage/grpc/proto/storage_test.proto
  plugin/storage/grpc/proto/storageprototest/storage_test.pb.go
Labels: changelog:bugfix-or-minor-feature

#4937 Make UI placeholder more descriptive
  cmd/query/app/ui/placeholder/index.html
Labels: changelog:bugfix-or-minor-feature

#4951 [kafka-consumer] Add topic name as a tag to offset manager metrics
  cmd/ingester/app/consumer/offset/manager.go
  cmd/ingester/app/consumer/offset/manager_test.go
  cmd/ingester/app/consumer/processor_factory.go
Labels: changelog:bugfix-or-minor-feature

#4957 Normalize metric names due to breaking change
  docker-compose/monitor/docker-compose.yml
Labels: changelog:bugfix-or-minor-feature

#4829 Support Elasticsearch 8.x
  .github/workflows/ci-elasticsearch.yml
  cmd/es-rollover/app/init/action.go
  cmd/es-rollover/app/init/flags.go
  cmd/es-rollover/app/init/flags_test.go
  go.mod
  go.sum
  pkg/es/client/client.go
  pkg/es/client/cluster_client.go
  pkg/es/client/cluster_client_test.go
  pkg/es/client/index_client.go
  pkg/es/client/index_client_test.go
  pkg/es/client/mocks/cluster_client.go
  pkg/es/config/config.go
  pkg/es/wrapper/wrapper.go
  plugin/storage/es/factory.go
  plugin/storage/es/mappings/fixtures/jaeger-dependencies-8.json
  plugin/storage/es/mappings/fixtures/jaeger-service-8.json
  plugin/storage/es/mappings/fixtures/jaeger-span-8.json
  plugin/storage/es/mappings/jaeger-dependencies-8.json
  plugin/storage/es/mappings/jaeger-service-8.json
  plugin/storage/es/mappings/jaeger-span-8.json
  plugin/storage/es/mappings/mapping.go
  plugin/storage/es/mappings/mapping_test.go
  plugin/storage/es/options.go
  plugin/storage/es/spanstore/writer.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/es_index_cleaner_test.go
  plugin/storage/integration/es_index_rollover_test.go
  scripts/es-integration-test.sh
Labels: changelog:new-feature

#4962 [ci/es] Use default template priorities
  plugin/storage/integration/elasticsearch_test.go
Labels: changelog:ci

#4964 Collect code coverage from integration tests and upload to codecov
  .codecov.yml
  .github/actions/setup-codecov/action.yml
  .github/workflows/ci-cassandra.yml
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-grpc-badger.yml
  .github/workflows/ci-kafka.yml
  .github/workflows/ci-opensearch.yml
  .github/workflows/ci-unit-tests.yml
  Makefile
  cmd/ingester/app/builder/.nocover
  cmd/ingester/app/builder/empty_test.go
  pkg/cassandra/config/.nocover
  pkg/cassandra/config/empty_test.go
  pkg/cassandra/gocql/.nocover
  pkg/cassandra/gocql/empty_test.go
  pkg/es/wrapper/.nocover
  pkg/es/wrapper/empty_test.go
  pkg/kafka/auth/.nocover
  pkg/kafka/auth/empty_test.go
  pkg/kafka/consumer/.nocover
  pkg/kafka/consumer/empty_test.go
  pkg/kafka/producer/.nocover
  pkg/kafka/producer/empty_test.go
  plugin/storage/badger/samplingstore/storage.go
  plugin/storage/grpc/config/.nocover
  plugin/storage/grpc/config/empty_test.go
  plugin/storage/integration/.nocover
  plugin/storage/integration/integration.go
Labels: changelog:ci

#4967 Declare all interfaces each factory implements
  plugin/storage/badger/factory.go
  plugin/storage/blackhole/factory.go
  plugin/storage/cassandra/factory.go
  plugin/storage/cassandra/factory_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
  plugin/storage/factory.go
  plugin/storage/factory_test.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/kafka/factory.go
  plugin/storage/kafka/factory_test.go
  plugin/storage/memory/factory.go
Labels: changelog:test

#4966 fix(badger): Add missing SamplingStoreFactory.CreateLock method
  plugin/storage/badger/factory.go
  plugin/storage/badger/factory_test.go
  plugin/storage/badger/lock.go
  plugin/storage/badger/lock_test.go
  plugin/storage/factory_test.go
Labels: changelog:bugfix-or-minor-feature

#4972 Add unit tests for jtracer package
  pkg/jtracer/.nocover
  pkg/jtracer/jtracer.go
  pkg/jtracer/jtracer_test.go
Labels: changelog:skip
