Repository jaegertracing/jaeger, pull requests merged in 2023-10, with the labels that each got.

#4847 CI: Add the label-check workflow to verify changelog labels on each PR
  .github/workflows/ci-label-check.yml
Labels: changelog:ci

#4796 Fix batchProcessor to set correct span format flags
  cmd/collector/app/handler/grpc_handler.go
  cmd/collector/app/handler/grpc_handler_test.go
Labels: changelog:bugfix-or-minor-feature

#4854 Use changelog:dependencies label for dependabot PRs
  .github/dependabot.yml
  scripts/release-notes.py
Labels: changelog:skip

#4857 chore: Add Dynamic Loading Bar Functionality to release-notes.py
  scripts/release-notes.py
Labels: changelog:ci

#4826 Add CI validation of shell scripts using shellcheck
  .github/workflows/ci-validation-of-shell-scripts.yml
  scripts/build-all-in-one-image.sh
  scripts/build-crossdock.sh
  scripts/build-upload-a-docker-image.sh
  scripts/cassandra-integration-test.sh
  scripts/check-go-version.sh
  scripts/check-test-files.sh
  scripts/compute-tags.sh
  scripts/es-integration-test.sh
  scripts/generate-help-output.sh
  scripts/hotrod-integration-test.sh
  scripts/import-order-cleanup.sh
  scripts/package-deploy.sh
  scripts/rebuild-ui.sh
  scripts/update-semconv-version.sh
  scripts/updateLicenses.sh
Labels: hacktoberfest, changelog:ci

#4864 Add OTel resource detector to Jaeger components
  cmd/tracegen/main.go
  pkg/jtracer/jtracer.go
Labels: changelog:bugfix-or-minor-feature

#4865 test[es]: Force batch size 1 in test
  plugin/storage/es/factory_test.go
Labels: changelog:test

#4870 Create scorecard.yml for OSSF implementation
  .github/workflows/scorecard.yml
Labels: changelog:ci

#4873 exp: Support primary and archive storage
  cmd/jaeger-v2/config-ui.json
  cmd/jaeger-v2/config.yaml
  cmd/jaeger-v2/internal/command.go
  cmd/jaeger-v2/internal/extension/jaegerquery/config.go
  cmd/jaeger-v2/internal/extension/jaegerquery/factory.go
  cmd/jaeger-v2/internal/extension/jaegerquery/server.go
  cmd/query/app/flags.go
  cmd/query/app/flags_test.go
  cmd/query/app/server_test.go
  cmd/query/app/static_handler.go
  cmd/query/app/static_handler_test.go
  cmd/query/app/token_propagation_test.go
  plugin/storage/memory/factory.go
Labels: changelog:exprimental

#4875 exp(jaeger-v2): Simplify all-in-one configuration
  cmd/jaeger-v2/internal/all-in-one.yaml
  cmd/jaeger-v2/internal/command.go
  cmd/jaeger-v2/internal/exporters/storageexporter/factory.go
  cmd/jaeger-v2/internal/extension/jaegerquery/factory.go
  cmd/jaeger-v2/internal/extension/jaegerstorage/factory.go
Labels: changelog:exprimental

#4872 Adding first pass at the SECURITY-INSIGHTS.yml
  README.md
  SECURITY-INSIGHTS.yml
Labels: changelog:ci

#4879 ci: Keep the UI asset's .gz file timestamps the same as the original file
  Makefile
Labels: changelog:ci

#4880 ci: Enable linting of code in examples/
  .golangci.yml
  Makefile
  examples/hotrod/cmd/.nocover
  examples/hotrod/cmd/frontend.go
  examples/hotrod/pkg/delay/.nocover
  examples/hotrod/pkg/httperr/.nocover
  examples/hotrod/pkg/log/.nocover
  examples/hotrod/pkg/pool/.nocover
  examples/hotrod/pkg/tracing/.nocover
  examples/hotrod/pkg/tracing/rpcmetrics/metrics.go
  examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go
  examples/hotrod/services/config/.nocover
  examples/hotrod/services/customer/.nocover
  examples/hotrod/services/customer/server.go
  examples/hotrod/services/driver/.nocover
  examples/hotrod/services/driver/driver.pb.go
  examples/hotrod/services/frontend/.nocover
  examples/hotrod/services/frontend/server.go
  examples/hotrod/services/route/.nocover
  examples/hotrod/services/route/server.go
  examples/hotrod/services/route/stats.go
Labels: changelog:ci

#4881 test: Add more linters
  .golangci.yml
  cmd/internal/status/command.go
  crossdock/main.go
  internal/metricstest/local.go
  pkg/es/client/client.go
  plugin/metrics/disabled/reader.go
  plugin/sampling/strategystore/static/strategy_store.go
Labels: changelog:ci

#4882 Simplify Makefile
  Makefile
Labels: changelog:ci

#4883 ci: Pass variable instead of calling make build-xxx-debug
  scripts/build-all-in-one-image.sh
  scripts/build-crossdock.sh
Labels: changelog:ci

#4884 test: Keep track of both passwords
  plugin/storage/es/factory_test.go
Labels: changelog:test

#4885 Simplify binary building in Makefile
  Makefile
Labels: changelog:ci

#4893 [chore] Bump otel collector contrib to v0.88.0
  go.mod
  go.sum
Labels: changelog:dependencies

#4834 feat: Add sampling store support to Badger
  plugin/storage/badger/factory.go
  plugin/storage/badger/samplingstore/storage.go
  plugin/storage/badger/samplingstore/storage_test.go
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/integration.go
Labels: changelog:new-feature

#4896 feat: Add blackhole storage, for benchmarking
  plugin/storage/blackhole/blackhole.go
  plugin/storage/blackhole/blackhole_test.go
  plugin/storage/blackhole/factory.go
  plugin/storage/blackhole/factory_test.go
  plugin/storage/factory.go
  plugin/storage/factory_config.go
Labels: changelog:bugfix-or-minor-feature

#4898 Add reload interval to OTel server certificates
  cmd/collector/app/flags/flags.go
  cmd/collector/app/flags/flags_test.go
  cmd/collector/app/handler/otlp_receiver.go
  cmd/collector/app/handler/otlp_receiver_test.go
  pkg/config/tlscfg/flags.go
  pkg/config/tlscfg/flags_test.go
  pkg/config/tlscfg/options.go
Labels: changelog:bugfix-or-minor-feature

#4902 Remove --otel-exporter=otlp argument from HotROD docker-compose
  examples/hotrod/docker-compose.yml
Labels: changelog:skip

#4907 fix dependency policy and add to SECURITY-INSIGHTS.yml
  SECURITY-INSIGHTS.yml
  SECURITY.md
  SELF-ASSESMENT.md
  THREAT-MODEL.md
Labels: changelog:bugfix-or-minor-feature

#4908 Add breaking change to 1.50 release notes
  CHANGELOG.md
Labels: changelog:skip
