Repository jaegertracing/jaeger, pull requests merged in 2023-12, with the labels that each got.

#4981 [test]: make Kafka consumer read from the earliest messages
  .github/workflows/ci-kafka.yml
  cmd/ingester/app/builder/builder.go
  pkg/kafka/consumer/config.go
  plugin/storage/integration/kafka_test.go
Labels: changelog:test

#4980 Fix example/grafana-integration
  examples/grafana-integration/README.md
  examples/grafana-integration/docker-compose.yaml
  examples/grafana-integration/grafana/hotrod_metrics_logs.json
  examples/grafana-integration/prometheus/prometheus.yml
Labels: changelog:bugfix-or-minor-feature

#4985 [SPM] Differentiate null from no error data
  docker-compose/monitor/Makefile
  docker-compose/monitor/README.md
  plugin/metrics/prometheus/metricsstore/reader.go
  plugin/metrics/prometheus/metricsstore/reader_test.go
  plugin/metrics/prometheus/metricsstore/testdata/empty_response.json
Labels: changelog:bugfix-or-minor-feature

#4989 [ci]:Improve Kafka integration test self-sufficiency
  .github/workflows/ci-kafka.yml
  scripts/kafka-integration-test.sh
Labels: changelog:ci

#4995 Remove custom GOCACHE location
  .github/workflows/ci-unit-tests.yml
  Makefile
Labels: changelog:ci

#5008 Make all-in-one metric names match metrics from standalone components
  cmd/all-in-one/main.go
Labels: changelog:breaking-change

#5011 Allow specifying version for HotROD docker-compose
  examples/hotrod/README.md
  examples/hotrod/docker-compose.yml
Labels: changelog:bugfix-or-minor-feature

#5010 Feature: add goleak to check goroutine leak in tests
  Makefile
  cmd/agent/app/configmanager/grpc/manager_test.go
  cmd/agent/app/customtransport/buffered_read_transport_test.go
  cmd/agent/app/httpserver/srv_test.go
  cmd/agent/app/processors/thrift_processor_test.go
  cmd/agent/app/servers/server_test.go
  cmd/agent/app/servers/thriftudp/transport_test.go
  go.mod
  go.sum
  model/trace_test.go
  scripts/check-goleak-files.sh
Labels: changelog:ci

#5015 Add goleak check to cmd/agent/app/configmanager
  cmd/agent/app/configmanager/metrics_test.go
Labels: changelog:ci

#5020 Move Go Tip installation into sub-action
  .github/actions/setup-go-tip/action.yml
  .github/workflows/ci-unit-tests-go-tip.yml
Labels: changelog:ci

#5022 ci: add retry logic in the Install Go Tip GitHub Action
  .github/actions/setup-go-tip/action.yml
Labels: changelog:ci

#5026 Fix goroutine leaks in several packages
  pkg/es/wrapper/wrapper.go
  pkg/jtracer/jtracer.go
  pkg/jtracer/jtracer_test.go
  pkg/queue/bounded_queue_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
  plugin/storage/es/package_test.go
  plugin/storage/grpc/memory/plugin_test.go
  plugin/storage/kafka/factory.go
  plugin/storage/kafka/factory_test.go
  plugin/storage/kafka/package_test.go
  plugin/storage/kafka/writer_test.go
  plugin/storage/memory/factory_test.go
  plugin/storage/memory/package_test.go
Labels: changelog:ci

#5028 Enable errorlint linter and fix errors
  .golangci.yml
  cmd/anonymizer/app/query/query.go
  cmd/anonymizer/app/uiconv/extractor.go
  cmd/anonymizer/app/uiconv/extractor_test.go
  cmd/anonymizer/app/uiconv/module.go
  cmd/anonymizer/app/uiconv/reader.go
  cmd/anonymizer/app/uiconv/reader_test.go
  cmd/collector/app/handler/grpc_handler.go
  cmd/es-rollover/app/init/action.go
  cmd/internal/flags/admin.go
  cmd/query/app/flags.go
  cmd/query/app/grpc_handler.go
  cmd/query/app/http_handler.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/server.go
  model/ids.go
  pkg/es/client/ilm_client.go
  pkg/es/client/index_client.go
  pkg/es/config/config.go
  plugin/storage/badger/factory.go
  plugin/storage/badger/samplingstore/storage.go
  plugin/storage/cassandra/samplingstore/storage.go
  plugin/storage/grpc/shared/grpc_client.go
  plugin/storage/grpc/shared/grpc_handler.go
Labels: changelog:skip

#5029 Upgrade golangci-lint to v1.55.2 and fix errors
  .golangci.yml
  Makefile
  cmd/agent/app/reporter/client_metrics.go
  cmd/agent/app/servers/tbuffered_server_test.go
  cmd/collector/app/root_span_handler_test.go
  cmd/collector/app/span_processor.go
  cmd/collector/app/span_processor_test.go
  cmd/es-rollover/app/actions_test.go
  cmd/es-rollover/app/index_options_test.go
  cmd/es-rollover/app/init/action_test.go
  cmd/es-rollover/app/lookback/time_reference_test.go
  cmd/es-rollover/app/rollover/action_test.go
  cmd/internal/flags/service_test.go
  pkg/es/filter/alias_test.go
  pkg/es/filter/date_test.go
  pkg/queue/bounded_queue.go
  pkg/queue/bounded_queue_test.go
  plugin/sampling/leaderelection/leader_election.go
  plugin/sampling/leaderelection/leader_election_test.go
  plugin/sampling/strategystore/static/strategy_store_test.go
  plugin/storage/badger/lock_test.go
  plugin/storage/cassandra/spanstore/writer_test.go
  plugin/storage/grpc/shared/streaming_writer.go
  plugin/storage/memory/lock_test.go
  plugin/storage/memory/sampling_test.go
Labels: changelog:test

#5033 ci: Simplify check-label workflow
  .github/workflows/ci-label-check.yml
Labels: changelog:ci

#5032 testifylint: enable bool-compare
  .golangci.yml
  cmd/agent/app/reporter/grpc/collector_proxy_test.go
  cmd/anonymizer/app/flags_test.go
  cmd/anonymizer/app/uiconv/reader_test.go
  cmd/collector/app/flags/flags_test.go
  cmd/collector/app/span_processor_test.go
  cmd/collector/app/zipkin/zipkindeser/json_test.go
  cmd/es-index-cleaner/app/flags_test.go
  cmd/es-rollover/app/actions_test.go
  cmd/es-rollover/app/flags_test.go
  model/span_test.go
  pkg/cache/lru_test.go
  plugin/metrics/prometheus/factory_test.go
  plugin/storage/cassandra/options_test.go
  plugin/storage/es/options_test.go
  plugin/storage/grpc/options_test.go
Labels: changelog:test

#5030 Publish test report
  .github/workflows/ci-unit-tests-go-tip.yml
  .github/workflows/ci-unit-tests.yml
  .gitignore
  Makefile
  model/keyvalue_test.go
Labels: changelog:ci

#5038 Fix goroutine leaks in some packages
  cmd/agent/app/reporter/client_metrics_test.go
  cmd/agent/app/reporter/connect_metrics_test.go
  cmd/agent/app/reporter/metrics_test.go
  cmd/agent/app/reporter/package_test.go
  pkg/httpmetrics/metrics_test.go
  pkg/recoveryhandler/zap_test.go
Labels: changelog:test

#5037 Refactor Protobuf types generation
  .github/workflows/ci-protogen-tests.yml
  Makefile
  Makefile.Crossdock.mk
  Makefile.Protobuf.mk
  Makefile.Thrift.mk
  otel_proto_patch.sed
Labels: changelog:ci

#5041 Fix permission failed on checks-run
  .github/workflows/ci-unit-tests-go-tip.yml
  .github/workflows/ci-unit-tests.yml
Labels: changelog:ci

#5040 Regenerate HotROD proto
  Makefile
  Makefile.Protobuf.mk
  examples/hotrod/services/driver/driver.pb.go
  model/converter/empty_test.go
  model/converter/thrift/empty_test.go
  pkg/empty_test.go
  scripts/import-order-cleanup.sh
  scripts/updateLicenses.sh
Labels: changelog:ci

#5039 Regenerate Thrift types and enable Thrift check
  .github/workflows/ci-protogen-tests.yml
  Makefile.Protobuf.mk
  thrift-gen/agent/GoUnusedProtection__.go
  thrift-gen/agent/agent-consts.go
  thrift-gen/agent/agent.go
  thrift-gen/baggage/GoUnusedProtection__.go
  thrift-gen/baggage/baggage-consts.go
  thrift-gen/baggage/baggage.go
  thrift-gen/jaeger/GoUnusedProtection__.go
  thrift-gen/jaeger/jaeger-consts.go
  thrift-gen/jaeger/jaeger.go
  thrift-gen/sampling/GoUnusedProtection__.go
  thrift-gen/sampling/sampling-consts.go
  thrift-gen/sampling/sampling.go
  thrift-gen/zipkincore/GoUnusedProtection__.go
  thrift-gen/zipkincore/zipkincore-consts.go
  thrift-gen/zipkincore/zipkincore.go
Labels: changelog:ci

#5044 Fix go tip unit test runs
  .github/actions/setup-go-tip/action.yml
Labels: changelog:test

#5046 Clean-up APIv3 tests
  cmd/query/app/apiv3/grpc_gateway.go
  cmd/query/app/apiv3/grpc_gateway_test.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/package_test.go
  cmd/query/app/server.go
Labels: changelog:test

#5048 Fix goroutine leaks in some packages
  crossdock/services/agent_test.go
  crossdock/services/pakcage_test.go
  crossdock/services/query_test.go
  examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go
  examples/hotrod/pkg/tracing/rpcmetrics/package_test.go
  internal/metrics/expvar/cache_test.go
  internal/metrics/expvar/package_test.go
  internal/metrics/fork/fork_test.go
Labels: changelog:test

#5045 💤 Swap Zipkin server for Zipkin Receiver from OTel Collector Contrib
  .codecov.yml
  .github/dependabot.yml
  Makefile
  cmd/anonymizer/app/uiconv/extractor_test.go
  cmd/collector/app/collector.go
  cmd/collector/app/collector_test.go
  cmd/collector/app/handler/testdata/zipkin_proto_01.json
  cmd/collector/app/handler/testdata/zipkin_proto_02.json
  cmd/collector/app/handler/testdata/zipkin_thrift_v1_merged_spans.json
  cmd/collector/app/handler/testdata/zipkin_v2_01.json
  cmd/collector/app/handler/testdata/zipkin_v2_02.json
  cmd/collector/app/handler/testdata/zipkin_v2_03.json
  cmd/collector/app/handler/thrift_span_handler_test.go
  cmd/collector/app/handler/zipkin_receiver.go
  cmd/collector/app/handler/zipkin_receiver_test.go
  cmd/collector/app/handler/zipkin_receiver_tls_test.go
  cmd/collector/app/server/zipkin.go
  cmd/collector/app/zipkin/http_handler.go
  cmd/collector/app/zipkin/http_handler_test.go
  cmd/collector/app/zipkin/zipkindeser/annotation.go
  cmd/collector/app/zipkin/zipkindeser/annotation_test.go
  cmd/collector/app/zipkin/zipkindeser/fixtures/zipkin_v1_merged_spans.json
  cmd/collector/app/zipkin/zipkindeser/json.go
  cmd/collector/app/zipkin/zipkindeser/json_test.go
  cmd/collector/app/zipkin/zipkindeser/jsonv2.go
  cmd/collector/app/zipkin/zipkindeser/jsonv2_test.go
  cmd/collector/app/zipkin/zipkindeser/package_test.go
  cmd/collector/app/zipkin/zipkindeser/protov2.go
  cmd/collector/app/zipkin/zipkindeser/protov2_test.go
  cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks.go
  cmd/collector/app/zipkin/zipkindeser/zipkindesermocks/mocks_test.go
  go.mod
  go.sum
  swagger-gen/models/annotation.go
  swagger-gen/models/endpoint.go
  swagger-gen/models/list_of_spans.go
  swagger-gen/models/span.go
  swagger-gen/models/tags.go
  swagger-gen/restapi/configure_zipkin_api.go
  swagger-gen/restapi/doc.go
  swagger-gen/restapi/embedded_spec.go
  swagger-gen/restapi/operations/post_spans.go
  swagger-gen/restapi/operations/post_spans_parameters.go
  swagger-gen/restapi/operations/post_spans_responses.go
  swagger-gen/restapi/operations/zipkin_api.go
  swagger-gen/restapi/operations/zipkin_api_api.go
Labels: changelog:breaking-change

#5051 Add grpc-gateway tests for all APIv3 methods
  cmd/query/app/apiv3/grpc_gateway_test.go
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithBasePathAndTLS_FindTraces.json
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithBasePathAndTLS_GetOperations.json
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithBasePathAndTLS_GetServices.json
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithBasePathAndTLS_GetTrace.json
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithTenancy_FindTraces.json
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithTenancy_GetOperations.json
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithTenancy_GetServices.json
  cmd/query/app/apiv3/snapshots/TestGRPCGatewayWithTenancy_GetTrace.json
  cmd/query/app/apiv3/snapshots/TestGRPCGateway_FindTraces.json
  cmd/query/app/apiv3/snapshots/TestGRPCGateway_GetOperations.json
  cmd/query/app/apiv3/snapshots/TestGRPCGateway_GetServices.json
  cmd/query/app/apiv3/snapshots/TestGRPCGateway_GetTrace.json
  cmd/query/app/http_handler.go
Labels: changelog:test

#5057 bugfix: Set pipefail when running unit tests to preserve exit code
  Makefile
Labels: bug, changelog:ci

#5061 Separate test report collection from the main target
  .github/workflows/ci-unit-tests-go-tip.yml
  .github/workflows/ci-unit-tests.yml
  Makefile
Labels: changelog:ci

#5060 Remove grpc-gateway dependency
  Makefile.Protobuf.mk
  cmd/all-in-one/all_in_one_test.go
  cmd/query/app/apiv3/gateway_test.go
  cmd/query/app/apiv3/grpc_gateway.go
  cmd/query/app/apiv3/grpc_gateway_test.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/server.go
  go.mod
  go.sum
  proto-gen/api_v3/query_service.pb.gw.go
Labels: changelog:bugfix-or-minor-feature
