Repository jaegertracing/jaeger, pull requests merged in 2024-05, with the labels that each got.

#5405 Combine jaeger UI release notes with jaeger backend
  Makefile
  scripts/release-notes.py
Labels: changelog:bugfix-or-minor-feature

#5399 [jaeger-v2] Define an internal interface of storage v2 spanstore
  storage_v2/empty_test.go
  storage_v2/factory.go
  storage_v2/spanstore/empty_test.go
  storage_v2/spanstore/factory.go
  storage_v2/spanstore/reader.go
  storage_v2/spanstore/writer.go
Labels: changelog:bugfix-or-minor-feature, v2

#5404 Upgrade mockery from v2.14.0 to v2.42.3
  Makefile
  pkg/es/mocks/Client.go
  pkg/es/mocks/ClusterAPI.go
  pkg/es/mocks/IndexAPI.go
  pkg/es/mocks/IndexManagementLifecycleAPI.go
  pkg/es/mocks/IndexService.go
  pkg/es/mocks/IndicesCreateService.go
  pkg/es/mocks/IndicesExistsService.go
  pkg/es/mocks/MultiSearchService.go
  pkg/es/mocks/SearchService.go
  pkg/es/mocks/TemplateApplier.go
  pkg/es/mocks/TemplateBuilder.go
  pkg/es/mocks/TemplateCreateService.go
  proto-gen/storage_v1/mocks/ArchiveSpanReaderPluginClient.go
  proto-gen/storage_v1/mocks/ArchiveSpanReaderPluginServer.go
  proto-gen/storage_v1/mocks/ArchiveSpanReaderPlugin_GetArchiveTraceClient.go
  proto-gen/storage_v1/mocks/ArchiveSpanReaderPlugin_GetArchiveTraceServer.go
  proto-gen/storage_v1/mocks/ArchiveSpanWriterPluginClient.go
  proto-gen/storage_v1/mocks/ArchiveSpanWriterPluginServer.go
  proto-gen/storage_v1/mocks/DependenciesReaderPluginClient.go
  proto-gen/storage_v1/mocks/DependenciesReaderPluginServer.go
  proto-gen/storage_v1/mocks/PluginCapabilitiesClient.go
  proto-gen/storage_v1/mocks/PluginCapabilitiesServer.go
  proto-gen/storage_v1/mocks/SpanReaderPluginClient.go
  proto-gen/storage_v1/mocks/SpanReaderPluginServer.go
  proto-gen/storage_v1/mocks/SpanReaderPlugin_FindTracesClient.go
  proto-gen/storage_v1/mocks/SpanReaderPlugin_FindTracesServer.go
  proto-gen/storage_v1/mocks/SpanReaderPlugin_GetTraceClient.go
  proto-gen/storage_v1/mocks/SpanReaderPlugin_GetTraceServer.go
  proto-gen/storage_v1/mocks/SpanWriterPluginClient.go
  proto-gen/storage_v1/mocks/SpanWriterPluginServer.go
  proto-gen/storage_v1/mocks/StreamingSpanWriterPluginClient.go
  proto-gen/storage_v1/mocks/StreamingSpanWriterPluginServer.go
  proto-gen/storage_v1/mocks/StreamingSpanWriterPlugin_WriteSpanStreamClient.go
  proto-gen/storage_v1/mocks/StreamingSpanWriterPlugin_WriteSpanStreamServer.go
  storage/spanstore/mocks/Reader.go
  storage/spanstore/mocks/Writer.go
Labels: changelog:dependencies

#5407 Add `Purge` method for ES/OS
  cmd/jaeger/internal/integration/storagecleaner/extension.go
  cmd/jaeger/internal/integration/storagecleaner/extension_test.go
  pkg/es/client.go
  pkg/es/config/config.go
  pkg/es/mocks/Client.go
  pkg/es/mocks/IndicesDeleteService.go
  pkg/es/wrapper/wrapper.go
  plugin/storage/badger/factory.go
  plugin/storage/es/factory.go
  plugin/storage/es/options.go
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/elasticsearch_test.go
  storage/factory.go
Labels: changelog:test

#5408 [es] Remove unused indexCache
  plugin/storage/es/spanstore/writer.go
  plugin/storage/es/spanstore/writer_test.go
Labels: changelog:bugfix-or-minor-feature

#5409 [tests] Simplify integration tests
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/cassandra_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/es_index_cleaner_test.go
  plugin/storage/integration/grpc_test.go
  plugin/storage/integration/kafka_test.go
Labels: changelog:test

#5410 Only build Docker images for Crossdock tests for linux/amd64
  Makefile.Crossdock.mk
Labels: changelog:ci

#5411 Use helper action to retry codecov uploads
  .github/actions/setup-codecov/action.yml
  .github/actions/upload-codecov/action.yml
  .github/workflows/ci-badger.yaml
  .github/workflows/ci-cassandra.yml
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-grpc.yml
  .github/workflows/ci-kafka.yml
  .github/workflows/ci-opensearch.yml
  .github/workflows/ci-unit-tests.yml
Labels: changelog:ci

#5345 [jaeger-v2] add elasticsearch & opensearch e2e integration test
  cmd/jaeger/config-elasticsearch.yaml
  cmd/jaeger/config-opensearch.yaml
  cmd/jaeger/internal/integration/badger_test.go
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/jaeger/internal/integration/es_test.go
  cmd/jaeger/internal/integration/grpc_test.go
  cmd/jaeger/internal/integration/os_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/options.go
  scripts/es-integration-test.sh
Labels: changelog:test

#5412 [v2] Add diagrams to the docs
  cmd/jaeger/internal/extension/remotesampling/README.md
  cmd/jaeger/internal/integration/README.md
Labels: changelog:bugfix-or-minor-feature

#5414 Add Purge method for cassandra
  plugin/storage/cassandra/factory.go
  plugin/storage/integration/cassandra_test.go
Labels: changelog:bugfix-or-minor-feature

#5413 Add missing mermaid markup
  cmd/jaeger/internal/extension/remotesampling/README.md
Labels: changelog:skip

#5398 [jaeger-v2] add cassandra e2e integration tests
  .github/workflows/ci-cassandra.yml
  cmd/jaeger/config-cassandra.yaml
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/integration/cassandra_test.go
  pkg/cassandra/config/config.go
  plugin/storage/cassandra/factory.go
  plugin/storage/cassandra/factory_test.go
  plugin/storage/cassandra/options.go
  plugin/storage/integration/cassandra_test.go
  plugin/storage/integration/integration.go
  scripts/cassandra-integration-test.sh
Labels: changelog:test

#5416 [bug] Fix syntax for invoking upload-codecov action
  .github/workflows/ci-cassandra.yml
  .github/workflows/ci-unit-tests.yml
Labels: changelog:ci

#5419 [jaeger-v2] Fix e2e storage integration v0.99.0 OTEL col failing
  cmd/jaeger/internal/exporters/storageexporter/factory.go
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/jaeger/internal/integration/span_writer.go
  go.mod
  go.sum
Labels: changelog:bugfix-or-minor-feature

#5417 Replace public InitFromOptions with private ConfigureFromOptions
  plugin/storage/badger/factory.go
  plugin/storage/badger/factory_test.go
  plugin/storage/cassandra/factory.go
  plugin/storage/cassandra/factory_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/kafka/factory.go
  plugin/storage/kafka/factory_test.go
  plugin/storage/memory/factory.go
  plugin/storage/memory/factory_test.go
Labels: changelog:bugfix-or-minor-feature

#5420 Enable Archive storage test for Cassandra
  plugin/storage/integration/cassandra_test.go
  scripts/cassandra-integration-test.sh
Labels: changelog:test

#5431 [v2] Change e2e jaeger-v2 binary log output to temp file
  .codecov.yml
  cmd/jaeger/internal/integration/e2e_integration.go
Labels: changelog:ci

#5433 [v2] Dump storage docker logs in Github CI if e2e test failed
  .github/workflows/ci-cassandra.yml
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-opensearch.yml
  scripts/cassandra-integration-test.sh
  scripts/es-integration-test.sh
Labels: changelog:ci

#5123 Add tests for internal/extension/jaegerquery
  cmd/jaeger/internal/extension/jaegerquery/.nocover
  cmd/jaeger/internal/extension/jaegerquery/config_test.go
  cmd/jaeger/internal/extension/jaegerquery/factory_test.go
  cmd/jaeger/internal/extension/jaegerquery/package_test.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
Labels: changelog:test

#5436 [v2] Remove temporary SkipBinaryAttrs flag from e2e tests
  cmd/jaeger/internal/integration/badger_test.go
  cmd/jaeger/internal/integration/cassandra_test.go
  cmd/jaeger/internal/integration/es_test.go
  cmd/jaeger/internal/integration/grpc_test.go
  cmd/jaeger/internal/integration/os_test.go
  plugin/storage/integration/integration.go
Labels: changelog:ci

#5393 [grpc-storage] Use grpc.NewClient
  plugin/storage/grpc/config/config.go
  plugin/storage/grpc/config/config_test.go
  plugin/storage/grpc/factory_test.go
Labels: changelog:bugfix-or-minor-feature

#5388 Deprecate gRPC-Plugin support
  .gitignore
  Makefile
  examples/memstore-plugin/README.md
  examples/memstore-plugin/main.go
  plugin/storage/grpc/README.md
  plugin/storage/grpc/config/config.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/grpc/grpc.go
  plugin/storage/grpc/memory/plugin.go
  plugin/storage/grpc/memory/plugin_test.go
  plugin/storage/grpc/options.go
  plugin/storage/grpc/options_test.go
  plugin/storage/grpc/shared/grpc_client.go
  plugin/storage/grpc/shared/grpc_handler.go
  plugin/storage/grpc/shared/interface.go
  plugin/storage/grpc/shared/plugin.go
  plugin/storage/grpc/shared/plugin_test.go
  plugin/storage/integration/grpc_test.go
  plugin/storage/integration/remote_memory_storage.go
Labels: changelog:breaking-change

#5440 Stop running integration tests for Elasticsearch v5/v6
  .github/workflows/ci-elasticsearch.yml
Labels: changelog:ci

#5442 Replace grpc-plugin storage type name with just grpc
  crossdock/jaeger-docker-compose.yml
  docker-compose/kafka/docker-compose.yml
  plugin/storage/factory.go
  plugin/storage/factory_config.go
  plugin/storage/grpc/factory.go
  scripts/generate-help-output.sh
Labels: changelog:bugfix-or-minor-feature

#5391 [query/tests] Use grpc.NewClient
  .github/workflows/ci-unit-tests.yml
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/server.go
  cmd/query/app/server_test.go
Labels: changelog:test

#5443 [v2] Replace e2e span_reader grpc.DialContext with NewClient
  cmd/jaeger/internal/integration/span_reader.go
Labels: changelog:ci

#5448 Remove support for Elasticsearch v5/v6
  plugin/storage/es/mappings/fixtures/jaeger-dependencies.json
  plugin/storage/es/mappings/fixtures/jaeger-sampling.json
  plugin/storage/es/mappings/fixtures/jaeger-service.json
  plugin/storage/es/mappings/fixtures/jaeger-span.json
  plugin/storage/es/mappings/jaeger-dependencies.json
  plugin/storage/es/mappings/jaeger-sampling.json
  plugin/storage/es/mappings/jaeger-service.json
  plugin/storage/es/mappings/jaeger-span.json
  plugin/storage/es/mappings/mapping.go
  plugin/storage/es/mappings/mapping_test.go
Labels: changelog:breaking-change

#5451 Remove elasticsearch v5/v6 from tests
  cmd/esmapping-generator/app/renderer/render_test.go
  plugin/storage/es/dependencystore/storage_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/es_index_rollover_test.go
Labels: changelog:ci

#5454 Fix alpine image to 3.19.0
  docker/Makefile
  docker/base/Dockerfile
  docker/debug/Dockerfile
  scripts/check-go-version.sh
Labels: changelog:bugfix-or-minor-feature

#5455 Avoid git warnings on shallow checkout
  .github/workflows/ci-lint-checks.yaml
  Makefile
Labels: changelog:skip

#5456 [v2] Add logging to read/write spans in e2e tests
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/jaeger/internal/integration/span_reader.go
  cmd/jaeger/internal/integration/span_writer.go
  plugin/storage/integration/integration.go
Labels: changelog:ci

#5457 Restore code coverage threshold back to 95%
  .codecov.yml
Labels: changelog:ci

#5460 [v2] Remove retries and increase timeout for e2e tests
  cmd/jaeger/internal/exporters/storageexporter/factory.go
  cmd/jaeger/internal/integration/span_writer.go
Labels: changelog:ci

#5461 [remote-storage] Add healthcheck to grpc server
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/jaeger/internal/integration/span_reader.go
  cmd/remote-storage/app/server.go
  plugin/storage/grpc/shared/grpc_handler.go
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/cassandra_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/grpc_test.go
  plugin/storage/integration/integration.go
  plugin/storage/integration/kafka_test.go
  plugin/storage/integration/remote_memory_storage.go
  plugin/storage/integration/trace_compare.go
  plugin/storage/integration/trace_compare_test.go
Labels: changelog:bugfix-or-minor-feature

#5465 Remove args and depict the image in From directive
  docker/base/Dockerfile
  docker/debug/Dockerfile
Labels: changelog:ci

#5331 Create new grpc storage configuration to align with OTEL
  cmd/jaeger/config-remote-storage.yaml
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  pkg/config/tlscfg/options.go
  pkg/config/tlscfg/options_test.go
  plugin/storage/grpc/config/config.go
  plugin/storage/grpc/config/config_test.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/grpc/options.go
  plugin/storage/grpc/options_test.go
Labels: v2, changelog:exprimental

#5467 fix: Close factory in plugin/storage/es/ test
  cmd/agent/app/reporter/grpc/collector_proxy_test.go
  plugin/storage/es/factory_test.go
Labels: changelog:test

#5441 Refactor Adaptive Sampling Aggregator & Strategy Store
  cmd/collector/app/sampling/strategystore/factory.go
  cmd/collector/main.go
  plugin/sampling/strategystore/adaptive/aggregator.go
  plugin/sampling/strategystore/adaptive/aggregator_test.go
  plugin/sampling/strategystore/adaptive/factory.go
  plugin/sampling/strategystore/adaptive/factory_test.go
  plugin/sampling/strategystore/adaptive/processor.go
  plugin/sampling/strategystore/adaptive/processor_test.go
  plugin/sampling/strategystore/adaptive/strategy_store.go
  plugin/sampling/strategystore/factory.go
  plugin/sampling/strategystore/factory_test.go
  plugin/sampling/strategystore/static/factory.go
  plugin/sampling/strategystore/static/factory_test.go
Labels: changelog:bugfix-or-minor-feature

#5482 Enable debug builds for ppc64le
  docker/debug/Dockerfile
Labels: changelog:ci

#5483 Bump Go to v1.22.3
  go.mod
Labels: changelog:dependencies

#5481 Upgrade OTEL to v1.27.0
  cmd/tracegen/main.go
  examples/hotrod/pkg/tracing/init.go
  examples/hotrod/pkg/tracing/rpcmetrics/observer.go
  examples/hotrod/pkg/tracing/rpcmetrics/observer_test.go
  examples/hotrod/services/customer/database.go
  go.mod
  go.sum
  model/adjuster/otel_tag.go
  model/adjuster/otel_tag_test.go
  pkg/jtracer/jtracer.go
  plugin/metrics/prometheus/metricsstore/reader.go
  plugin/storage/cassandra/spanstore/reader.go
Labels: changelog:dependencies

#5478 [refactor] move root span handler into aggregator
  cmd/collector/app/collector.go
  cmd/collector/app/collector_test.go
  cmd/collector/app/root_span_handler.go
  cmd/collector/app/root_span_handler_test.go
  cmd/collector/app/sampling/strategystore/interface.go
  plugin/sampling/strategystore/adaptive/aggregator.go
  plugin/sampling/strategystore/adaptive/aggregator_test.go
Labels: changelog:bugfix-or-minor-feature

#5487 Split v1 and v2 ES/OS integration tests
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-opensearch.yml
  scripts/es-integration-test.sh
Labels: changelog:ci

#5489 Revert #5482 - ppc64le is not yet supported by delve
  docker/debug/Dockerfile
Labels: changelog:skip

#5491 Remove support for Elasticsearch v5 and v6 #5439
  plugin/storage/es/README.md
Labels: changelog:skip

#5437 Remove support for expvar-backed metrics
  cmd/agent/main.go
  cmd/all-in-one/main.go
  cmd/collector/main.go
  examples/hotrod/cmd/flags.go
  examples/hotrod/cmd/root.go
  go.mod
  go.sum
  internal/metrics/expvar/factory.go
  internal/metrics/expvar/factory_test.go
  internal/metrics/expvar/metrics.go
  internal/metrics/expvar/metrics_test.go
  internal/metrics/metricsbuilder/builder.go
  internal/metrics/metricsbuilder/builder_test.go
Labels: changelog:breaking-change

#5490 Use docker compose for elasticsearch/opensearch integration tests
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-opensearch.yml
  docker-compose/elasticsearch/v7.yml
  docker-compose/elasticsearch/v8.yml
  docker-compose/opensearch/v1.yml
  docker-compose/opensearch/v2.yml
  scripts/es-integration-test.sh
Labels: changelog:ci

#5502 [test] Use locks to avoid race condition
  plugin/sampling/strategystore/adaptive/processor_test.go
Labels: changelog:test

#5496 Replace internal metrics.Factory usage with direct calls to expvar
  cmd/agent/app/agent_test.go
  cmd/agent/app/builder.go
  cmd/agent/app/builder_test.go
  cmd/agent/main.go
  cmd/all-in-one/main.go
  cmd/collector/app/collector.go
  cmd/collector/app/collector_test.go
  cmd/collector/main.go
  internal/metrics/expvar/cache.go
  internal/metrics/expvar/cache_test.go
  internal/metrics/expvar/factory.go
  internal/metrics/expvar/factory_test.go
  internal/metrics/expvar/metrics.go
  internal/metrics/expvar/metrics_test.go
  internal/metrics/fork/fork.go
  internal/metrics/fork/fork_test.go
  internal/safeexpvar/safeexpvar.go
  internal/safeexpvar/safeexpvar_test.go
  plugin/storage/factory.go
  plugin/storage/factory_test.go
  plugin/storage/memory/factory.go
  plugin/storage/memory/factory_test.go
Labels: changelog:bugfix-or-minor-feature

#5503 [agent/test] Wait for goroutine to exit
  cmd/agent/app/agent.go
Labels: changelog:test

#5500 Use docker compose for kafka integration tests
  .github/dependabot.yml
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-kafka.yml
  .github/workflows/ci-opensearch.yml
  docker-compose/kafka-integration-test/v3.yml
  scripts/es-integration-test.sh
  scripts/kafka-integration-test.sh
Labels: changelog:ci
