Repository jaegertracing/jaeger, pull requests merged in 2024-06, with the labels that each got.

#5501 Add Elasticsearch helper binaries to release
  Makefile
  scripts/package-deploy.sh
Labels: changelog:bugfix-or-minor-feature

#5505 Enable revive linter
  .golangci.yml
  cmd/agent/app/processors/thrift_processor_test.go
  cmd/agent/app/reporter/metrics_test.go
  cmd/collector/app/span_processor_test.go
  cmd/ingester/app/consumer/consumer.go
  cmd/internal/flags/service_test.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/internal/api_v3/traces.go
Labels: changelog:test

#5508 Add nolintlint linter
  .golangci.yml
  cmd/agent/app/reporter/grpc/reporter_test.go
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  storage/spanstore/downsampling_writer_test.go
Labels: changelog:ci

#5511 Enable Lint Rule: unexported-naming
  .golangci.yml
  cmd/collector/app/flags/flags_test.go
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/query/app/server_test.go
Labels: changelog:ci

#5512 Enable Lint Rules: bare-return & empty-lines
  .golangci.yml
  cmd/collector/app/collector.go
  cmd/query/app/server.go
  cmd/query/app/server_test.go
  pkg/fswatcher/fswatcher_test.go
  pkg/gzipfs/gzip.go
  pkg/httpmetrics/metrics.go
  pkg/kafka/auth/plaintext.go
  plugin/sampling/strategystore/static/strategy_store.go
  plugin/storage/badger/spanstore/reader.go
  plugin/storage/cassandra/spanstore/reader_test.go
  plugin/storage/memory/memory.go
Labels: changelog:ci

#5513 Enable Lint Rule: dot-imports
  .golangci.yml
  internal/metrics/prometheus/factory_test.go
  pkg/healthcheck/handler_test.go
  storage/metricsstore/metrics/decorator_test.go
  storage/spanstore/composite_test.go
  storage/spanstore/metrics/decorator_test.go
Labels: changelog:ci

#5517 Enable Lint Rule: modifies-value-receiver
  .golangci.yml
  cmd/agent/app/builder.go
  model/dependencies.go
Labels: changelog:ci

#5520 Use docker compose for cassandra integration tests
  .github/dependabot.yml
  .github/workflows/ci-cassandra.yml
  docker-compose/cassandra/v3.yaml
  docker-compose/cassandra/v4.yaml
  scripts/cassandra-integration-test.sh
Labels: changelog:ci

#5528 Add manual DCO check using Python script dco-check
  .github/workflows/ci-lint-checks.yaml
  scripts/dco_check.py
Labels: changelog:ci

#5524 Enable Lint Rules: confusing-results & receiver-naming
  .golangci.yml
  model/converter/thrift/zipkin/to_domain.go
  pkg/config/tlscfg/options.go
  plugin/storage/es/mappings/mapping.go
Labels: changelog:ci

#5525 Enable Lint Rule: exported
  .golangci.yml
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  plugin/storage/es/dependencystore/storage.go
  plugin/storage/es/dependencystore/storage_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/samplingstore/storage.go
  plugin/storage/es/samplingstore/storage_test.go
  plugin/storage/grpc/config.go
  plugin/storage/grpc/config/empty_test.go
  plugin/storage/grpc/config_test.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/grpc/options.go
  plugin/storage/grpc/options_test.go
Labels: changelog:ci

#5533 Enable Lint Rules: struct-tag & unexported-return
  .golangci.yml
  pkg/config/tlscfg/options.go
  plugin/storage/grpc/shared/grpc_client.go
  plugin/storage/grpc/shared/grpc_client_test.go
Labels: changelog:ci

#5543 Set desired providers/converters instead of relying on defaults
  cmd/jaeger/internal/command.go
  go.mod
Labels: changelog:bugfix-or-minor-feature

#5546 changing how major version is passed
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-opensearch.yml
  scripts/es-integration-test.sh
Labels: changelog:ci

#5556 Add workflow to validate dependabot config
  .github/dependabot.yml
  .github/workflows/validate-dependabot-config.yml
Labels: changelog:ci

#5539 Remove support for OTEL spanmetrics processor
  docker-compose/monitor/Makefile
  docker-compose/monitor/README.md
  docker-compose/monitor/otel-collector-config-processor.yml
  pkg/prometheus/config/config.go
  plugin/metrics/prometheus/factory_test.go
  plugin/metrics/prometheus/metricsstore/dbmodel/to_domain.go
  plugin/metrics/prometheus/metricsstore/dbmodel/to_domain_test.go
  plugin/metrics/prometheus/metricsstore/reader.go
  plugin/metrics/prometheus/metricsstore/reader_test.go
  plugin/metrics/prometheus/metricsstore/testdata/service_span_name_datapoint_response.json
  plugin/metrics/prometheus/options.go
Labels: changelog:breaking-change

#5558 Use esVersion >=7
  cmd/esmapping-generator/app/flags_test.go
Labels: changelog:test

#5560 Attempt another fix to dependabot config
  .github/dependabot.yml
Labels: changelog:dependencies

#5562 Fix .github/dependabot.yml
  .github/dependabot.yml
Labels: changelog:dependencies

#5561 Fix binary path in package-deploy.sh
  scripts/package-deploy.sh
Labels: changelog:bugfix-or-minor-feature

#5566 [dependabot config] Remove invalid path
  .github/dependabot.yml
Labels: changelog:dependencies

#5589 Fix new warnings from the linter upgrade
  .golangci.yml
Labels: changelog:ci

#5559 [query] Avoid errors when closing shared listener
  cmd/query/app/server.go
  cmd/query/app/server_test.go
Labels: changelog:bugfix-or-minor-feature

#5612 Require Renovate bot to run go mod tidy
  renovate.json
Labels: changelog:ci

#5622 Update Renovate bot to not apply patches to e2e test dependencies
  renovate.json
Labels: changelog:ci

#5625 Update opensearchproject/opensearch to v2.14.0
  docker-compose/opensearch/v2/docker-compose.yml
Labels: changelog:dependencies

#5623 Create config file for Mockery instead of using explicit CLI flags in the Makefile
  .mockery.yaml
  Makefile
  cmd/es-rollover/app/init/action_test.go
  cmd/es-rollover/app/lookback/action_test.go
  cmd/es-rollover/app/rollover/action_test.go
  pkg/es/client/mocks/ClusterAPI.go
  pkg/es/client/mocks/IndexAPI.go
  pkg/es/client/mocks/IndexManagementLifecycleAPI.go
  pkg/es/client/mocks/cluster_client.go
  pkg/es/client/mocks/ilm_client.go
  pkg/es/client/mocks/index_client.go
Labels: changelog:ci

#5619 Upgrade Badger v3->Badger v4
  go.mod
  go.sum
  plugin/storage/badger/factory.go
  plugin/storage/badger/factory_test.go
  plugin/storage/badger/samplingstore/storage.go
  plugin/storage/badger/samplingstore/storage_test.go
  plugin/storage/badger/spanstore/cache.go
  plugin/storage/badger/spanstore/cache_test.go
  plugin/storage/badger/spanstore/reader.go
  plugin/storage/badger/spanstore/rw_internal_test.go
  plugin/storage/badger/spanstore/writer.go
Labels: changelog:new-feature

#5590 Add semver to dependencies
  .github/workflows/codeql.yml
  .github/workflows/fossa.yml
  .github/workflows/validate-dependabot-config.yml
Labels: changelog:ci

#5618 Add alternate way to install gotip
  .github/actions/setup-go-tip/action.yml
Labels: changelog:ci

#5634 Rename strategy store to sampling strategy provider
  cmd/all-in-one/main.go
  cmd/collector/app/collector.go
  cmd/collector/app/collector_test.go
  cmd/collector/app/sampling/grpc_handler.go
  cmd/collector/app/sampling/samplingstrategy/empty_test.go
  cmd/collector/app/sampling/samplingstrategy/factory.go
  cmd/collector/app/sampling/samplingstrategy/interface.go
  cmd/collector/app/server/grpc.go
  cmd/collector/app/server/grpc_test.go
  cmd/collector/app/server/http.go
  cmd/collector/app/server/http_test.go
  cmd/collector/app/server/test.go
  cmd/collector/main.go
  cmd/internal/env/command.go
  pkg/clientcfg/clientcfghttp/cfgmgr.go
  pkg/clientcfg/clientcfghttp/cfgmgr_test.go
  pkg/clientcfg/clientcfghttp/handler_test.go
  plugin/sampling/strategyprovider/adaptive/aggregator.go
  plugin/sampling/strategyprovider/adaptive/aggregator_test.go
  plugin/sampling/strategyprovider/adaptive/cache.go
  plugin/sampling/strategyprovider/adaptive/cache_test.go
  plugin/sampling/strategyprovider/adaptive/calculationstrategy/interface.go
  plugin/sampling/strategyprovider/adaptive/calculationstrategy/interface_test.go
  plugin/sampling/strategyprovider/adaptive/calculationstrategy/package_test.go
  plugin/sampling/strategyprovider/adaptive/calculationstrategy/percentage_increase_capped_calculator.go
  plugin/sampling/strategyprovider/adaptive/calculationstrategy/percentage_increase_capped_calculator_test.go
  plugin/sampling/strategyprovider/adaptive/factory.go
  plugin/sampling/strategyprovider/adaptive/factory_test.go
  plugin/sampling/strategyprovider/adaptive/floatutils.go
  plugin/sampling/strategyprovider/adaptive/floatutils_test.go
  plugin/sampling/strategyprovider/adaptive/options.go
  plugin/sampling/strategyprovider/adaptive/options_test.go
  plugin/sampling/strategyprovider/adaptive/package_test.go
  plugin/sampling/strategyprovider/adaptive/processor.go
  plugin/sampling/strategyprovider/adaptive/processor_test.go
  plugin/sampling/strategyprovider/adaptive/provider.go
  plugin/sampling/strategyprovider/adaptive/weightvectorcache.go
  plugin/sampling/strategyprovider/adaptive/weightvectorcache_test.go
  plugin/sampling/strategyprovider/factory.go
  plugin/sampling/strategyprovider/factory_config.go
  plugin/sampling/strategyprovider/factory_config_test.go
  plugin/sampling/strategyprovider/factory_test.go
  plugin/sampling/strategyprovider/package_test.go
  plugin/sampling/strategyprovider/static/constants.go
  plugin/sampling/strategyprovider/static/factory.go
  plugin/sampling/strategyprovider/static/factory_test.go
  plugin/sampling/strategyprovider/static/fixtures/TestServiceNoPerOperationStrategiesDeprecatedBehavior_ServiceA.json
  plugin/sampling/strategyprovider/static/fixtures/TestServiceNoPerOperationStrategiesDeprecatedBehavior_ServiceB.json
  plugin/sampling/strategyprovider/static/fixtures/TestServiceNoPerOperationStrategies_ServiceA.json
  plugin/sampling/strategyprovider/static/fixtures/TestServiceNoPerOperationStrategies_ServiceB.json
  plugin/sampling/strategyprovider/static/fixtures/bad_strategies.json
  plugin/sampling/strategyprovider/static/fixtures/missing-service-types.json
  plugin/sampling/strategyprovider/static/fixtures/operation_strategies.json
  plugin/sampling/strategyprovider/static/fixtures/service_no_per_operation.json
  plugin/sampling/strategyprovider/static/fixtures/strategies.json
  plugin/sampling/strategyprovider/static/options.go
  plugin/sampling/strategyprovider/static/package_test.go
  plugin/sampling/strategyprovider/static/provider.go
  plugin/sampling/strategyprovider/static/provider_test.go
  plugin/sampling/strategyprovider/static/strategy.go
Labels: changelog:bugfix-or-minor-feature

#5638 Add tests for anonymizer/app/query.
  cmd/anonymizer/app/query/.nocover
  cmd/anonymizer/app/query/package_test.go
  cmd/anonymizer/app/query/query.go
  cmd/anonymizer/app/query/query_test.go
  cmd/anonymizer/main.go
Labels: changelog:ci

#5628 Add Flag for Custom Authenticators in Cassandra Storage
  pkg/cassandra/config/config.go
  plugin/storage/cassandra/options.go
  plugin/storage/cassandra/options_test.go
  plugin/storage/integration/cassandra_test.go
Labels: changelog:bugfix-or-minor-feature

#5642 Remove unnecessary .nocover files
  cmd/all-in-one/.nocover
  cmd/all-in-one/all_in_one_test.go
  cmd/all-in-one/package_test.go
  cmd/anonymizer/app/anonymizer/.nocover
  cmd/anonymizer/app/anonymizer/package_test.go
  cmd/internal/flags/.nocover
  cmd/internal/flags/admin.go
  cmd/internal/flags/admin_test.go
  cmd/internal/flags/package_test.go
Labels: changelog:ci

#5655 Group Renovate bot updates
  renovate.json
Labels: changelog:dependencies

#5497 [v2] Add v1 factory converter to v2 storage factory
  cmd/jaeger/internal/exporters/storageexporter/exporter.go
  cmd/jaeger/internal/exporters/storageexporter/exporter_test.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
  cmd/jaeger/internal/extension/jaegerstorage/factoryadapter/README.md
  cmd/jaeger/internal/extension/jaegerstorage/factoryadapter/factory.go
  cmd/jaeger/internal/extension/jaegerstorage/factoryadapter/factory_test.go
  cmd/jaeger/internal/extension/jaegerstorage/factoryadapter/package_test.go
  cmd/jaeger/internal/extension/jaegerstorage/factoryadapter/writer.go
  cmd/jaeger/internal/extension/jaegerstorage/factoryadapter/writer_test.go
Labels: changelog:new-feature

#5663 Add SPM build to CI
  .github/workflows/ci-build-spm.yml
  Makefile.Crossdock.mk
  docker-compose/monitor/Makefile
  docker/Makefile
Labels: changelog:ci

#5664 Use image digests for docker-compose files
  docker-compose/cassandra/v3/docker-compose.yaml
  docker-compose/cassandra/v4/docker-compose.yaml
  docker-compose/elasticsearch/v7/docker-compose.yml
  docker-compose/elasticsearch/v8/docker-compose.yml
  docker-compose/kafka-integration-test/docker-compose.yml
  docker-compose/monitor/docker-compose.yml
  docker-compose/opensearch/v1/docker-compose.yml
  docker-compose/opensearch/v2/docker-compose.yml
Labels: changelog:dependencies

#5673 Restore "operation" name in the metrics response
  plugin/metrics/prometheus/metricsstore/dbmodel/to_domain.go
  plugin/metrics/prometheus/metricsstore/dbmodel/to_domain_test.go
  plugin/metrics/prometheus/metricsstore/reader.go
  plugin/metrics/prometheus/metricsstore/reader_test.go
Labels: changelog:bugfix-or-minor-feature

#5674 Update changelog with patch release 1.58.1
  CHANGELOG.md
  scripts/release-notes.py
Labels: changelog:skip

#5675 Add better logging options
  cmd/internal/flags/flags.go
  cmd/internal/flags/service.go
  pkg/es/config/config.go
Labels: changelog:bugfix-or-minor-feature

#5640 Add SPM integration tests
  .github/workflows/ci-build-spm.yml
  docker-compose/monitor/Makefile
  scripts/spm-integration-test.sh
Labels: changelog:ci

#5661 Create metrics.Factory adapter for OTEL Metrics
  internal/metrics/benchmark_test.go
  internal/metrics/otelmetrics/counter.go
  internal/metrics/otelmetrics/factory.go
  internal/metrics/otelmetrics/factory_test.go
  internal/metrics/otelmetrics/gauge.go
  internal/metrics/otelmetrics/histogram.go
  internal/metrics/otelmetrics/timer.go
Labels: changelog:exprimental

#5690 Simplify configs organization
  cmd/jaeger/internal/exporters/storageexporter/exporter_test.go
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
  pkg/memory/config/empty_test.go
  plugin/storage/grpc/factory.go
  plugin/storage/memory/config.go
  plugin/storage/memory/factory.go
  plugin/storage/memory/factory_test.go
  plugin/storage/memory/memory.go
  plugin/storage/memory/memory_test.go
  plugin/storage/memory/options.go
Labels: area/storage, changelog:bugfix-or-minor-feature, changelog:skip
