Repository jaegertracing/jaeger, pull requests merged in 2024-04, with the labels that each got.

#5316 Allow go-leak linter to fail CI
  scripts/check-goleak-files.sh
Labels: changelog:ci

#5314 Fix breaking change in upgrading OTEL Collector
  cmd/jaeger/internal/components_test.go
  cmd/jaeger/internal/exporters/storageexporter/factory.go
  cmd/jaeger/internal/extension/jaegerquery/factory.go
  cmd/jaeger/internal/extension/jaegerstorage/factory.go
  cmd/jaeger/internal/integration/integration.go
  cmd/jaeger/internal/integration/receivers/storagereceiver/factory.go
  go.mod
  go.sum
Labels: changelog:dependencies

#5313 [es cit] Use storage factory instead of manual creation
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/integration.go
Labels: changelog:test

#5311 Fix goroutine leaks raised by plugin/storage/integration/cassandra_test.go
  plugin/storage/cassandra/factory.go
  plugin/storage/cassandra/factory_test.go
  plugin/storage/integration/cassandra_test.go
Labels: changelog:test

#5322 [jaeger-v2] add gRPC integration e2e test mode
  .codecov.yml
  .github/workflows/ci-grpc.yml
  Makefile
  cmd/jaeger/grpc_config.yaml
  cmd/jaeger/internal/integration/README.md
  cmd/jaeger/internal/integration/datareceivers/.nocover
  cmd/jaeger/internal/integration/datareceivers/jaegerstorage.go
  cmd/jaeger/internal/integration/fixtures/generated_pict_pairs_spans.txt
  cmd/jaeger/internal/integration/fixtures/generated_pict_pairs_traces.txt
  cmd/jaeger/internal/integration/fixtures/grpc_config.yaml
  cmd/jaeger/internal/integration/fixtures/pict_input_spans.txt
  cmd/jaeger/internal/integration/fixtures/pict_input_traces.txt
  cmd/jaeger/internal/integration/grpc_test.go
  cmd/jaeger/internal/integration/integration-diagram.png
  cmd/jaeger/internal/integration/integration.go
  cmd/jaeger/internal/integration/package_test.go
  cmd/jaeger/internal/integration/span_reader.go
  cmd/jaeger/internal/integration/span_writer.go
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/cassandra_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/es_index_cleaner_test.go
  plugin/storage/integration/es_index_rollover_test.go
  plugin/storage/integration/grpc_test.go
  plugin/storage/integration/integration.go
  plugin/storage/integration/kafka_test.go
  plugin/storage/integration/memstore_test.go
  plugin/storage/integration/remote_memory_storage.go
Labels: changelog:test

#5340 Fix goroutine leaks in grpc integration tests
  plugin/storage/grpc/config/config.go
  plugin/storage/grpc/factory.go
  plugin/storage/integration/grpc_test.go
Labels: changelog:test

#5358 [storage integration tests] Remove Refresh
  cmd/jaeger/internal/integration/grpc_test.go
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/cassandra_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/grpc_test.go
  plugin/storage/integration/integration.go
  plugin/storage/integration/kafka_test.go
  plugin/storage/integration/memstore_test.go
Labels: changelog:test

#5362 Fix the spelling of `remote` in log message
  plugin/storage/grpc/options.go
Labels: changelog:skip

#5365 Update security files and other governance files for best practices
  CODE_OF_CONDUCT.md
  GOVERNANCE.md
  MAINTAINERS.md
Labels: changelog:skip

#5367 Fixing capitalization
  MAINTAINERS.md
Labels: changelog:skip

#5369 Adding best practices badge to README.md
  README.md
Labels: changelog:bugfix-or-minor-feature

#5366 Add `CleanUp` method for badger storage
  plugin/storage/badger/factory.go
  plugin/storage/integration/badgerstore_test.go
Labels: changelog:ci, changelog:test

#5370 Moving global write permissions down into the CI jobs
  .github/workflows/ci-label-check.yml
  .github/workflows/ci-release.yml
  .github/workflows/ci-unit-tests-go-tip.yml
  .github/workflows/ci-unit-tests.yml
Labels: changelog:ci

#5371 Fixing up README badges and adding CLOMonitor
  README.md
Labels: changelog:skip

#5372 Deleted unused grpc-integration-test script
  scripts/grpc-integration-test.sh
Labels: changelog:skip

#5374 [bug-kafka-consumer] set the passedin rackid in consumer config
  cmd/ingester/app/builder/builder.go
  pkg/config/tlscfg/options.go
  storage/spanstore/downsampling_writer_test.go
Labels: changelog:bugfix-or-minor-feature

#5349 Create sampling templates when creating sampling store
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
  plugin/storage/es/samplingstore/storage.go
  plugin/storage/es/samplingstore/storage_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/integration.go
  storage/factory.go
Labels: changelog:bugfix-or-minor-feature

#5277 [sampling] Fix merging of per-operation strategies into service strategies without them
  plugin/sampling/strategystore/static/fixtures/TestServiceNoPerOperationStrategiesDeprecatedBehavior_ServiceA.json
  plugin/sampling/strategystore/static/fixtures/TestServiceNoPerOperationStrategiesDeprecatedBehavior_ServiceB.json
  plugin/sampling/strategystore/static/fixtures/TestServiceNoPerOperationStrategies_ServiceA.json
  plugin/sampling/strategystore/static/fixtures/TestServiceNoPerOperationStrategies_ServiceB.json
  plugin/sampling/strategystore/static/fixtures/service_no_per_operation.json
  plugin/sampling/strategystore/static/options.go
  plugin/sampling/strategystore/static/strategy_store.go
  plugin/sampling/strategystore/static/strategy_store_test.go
Labels: changelog:bugfix-or-minor-feature

#5383 Adding artifacthub badge
  README.md
Labels: changelog:skip

#5355 [jaeger-v2] add badger e2e integration test
  .github/workflows/ci-badger.yaml
  cmd/jaeger/badger_config.yaml
  cmd/jaeger/internal/components.go
  cmd/jaeger/internal/integration/badger_test.go
  cmd/jaeger/internal/integration/grpc_test.go
  cmd/jaeger/internal/integration/integration.go
  cmd/jaeger/internal/integration/receivers/storagereceiver/testdata/config.yaml
  cmd/jaeger/internal/integration/storagecleaner/README.md
  cmd/jaeger/internal/integration/storagecleaner/config.go
  cmd/jaeger/internal/integration/storagecleaner/config_test.go
  cmd/jaeger/internal/integration/storagecleaner/extension.go
  cmd/jaeger/internal/integration/storagecleaner/extension_test.go
  cmd/jaeger/internal/integration/storagecleaner/factory.go
  cmd/jaeger/internal/integration/storagecleaner/factory_test.go
  cmd/jaeger/internal/integration/storagecleaner/package_test.go
  go.mod
  plugin/storage/badger/factory.go
  storage/factory.go
Labels: changelog:test

#5392 [agent] Use grpc.NewClient
  cmd/agent/app/reporter/grpc/builder.go
  cmd/agent/app/reporter/grpc/builder_test.go
Labels: changelog:bugfix-or-minor-feature

#5400 [jaeger-v2] Normalize config names
  cmd/jaeger/config-badger.yaml
  cmd/jaeger/config-cassandra.yaml
  cmd/jaeger/config-remote-storage.yaml
  cmd/jaeger/internal/integration/badger_test.go
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/jaeger/internal/integration/grpc_test.go
Labels: changelog:skip
