Repository jaegertracing/jaeger, pull requests merged in 2024-02, with the labels that each got.

#5171 [jaeger-v2] Streamline storage initialization
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
Labels: changelog:bugfix-or-minor-feature

#5179 Add missing headers to the changelog
  CHANGELOG.md
Labels: changelog:skip

#5180 Bump Go version
  .github/workflows/ci-all-in-one-build.yml
  .github/workflows/ci-build-binaries.yml
  .github/workflows/ci-cassandra.yml
  .github/workflows/ci-crossdock.yml
  .github/workflows/ci-docker-build.yml
  .github/workflows/ci-elasticsearch.yml
  .github/workflows/ci-grpc-badger.yml
  .github/workflows/ci-hotrod.yml
  .github/workflows/ci-kafka.yml
  .github/workflows/ci-lint-checks.yaml
  .github/workflows/ci-opensearch.yml
  .github/workflows/ci-protogen-tests.yml
  .github/workflows/ci-release.yml
  .github/workflows/ci-unit-tests.yml
  .github/workflows/fossa.yml
  .golangci.yml
  docker/Makefile
  go.mod
Labels: changelog:bugfix-or-minor-feature

#5188 Release notes update
  RELEASE.md
Labels: changelog:skip

#5182 Upgrade otel collector to v0.94.0
  cmd/collector/app/handler/otlp_receiver.go
  cmd/collector/app/handler/otlp_receiver_test.go
  go.mod
  go.sum
Labels: changelog:dependencies

#5162 Add unit tests for anonymizer/app/writer
  cmd/anonymizer/app/writer/.nocover
  cmd/anonymizer/app/writer/writer.go
  cmd/anonymizer/app/writer/writer_test.go
  cmd/anonymizer/main.go
Labels: changelog:test

#5155 Support uploading traces to UI in OpenTelemetry format (OTLP JSON)
  cmd/query/app/fixture/otlp2jaeger-in.json
  cmd/query/app/fixture/otlp2jaeger-out.json
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/otlp_translator.go
Labels: changelog:new-feature

#5197 Add test for plugin/storage/grpc/shared
  plugin/storage/grpc/shared/plugin_test.go
Labels: changelog:test

#5209 Return more detailed errors from ES storage
  pkg/es/errors.go
  pkg/es/errors_test.go
  plugin/storage/es/spanstore/reader.go
  plugin/storage/es/spanstore/service_operation.go
Labels: changelog:bugfix-or-minor-feature

#5200 Add the print-config subcommand
  cmd/all-in-one/main.go
  cmd/collector/main.go
  cmd/ingester/main.go
  cmd/internal/printconfig/command.go
  cmd/internal/printconfig/command_test.go
  cmd/jaeger/main.go
  cmd/query/main.go
  cmd/remote-storage/main.go
Labels: changelog:bugfix-or-minor-feature

#5212 Move CODEOWNERS to .github/
  .github/CODEOWNERS
Labels: changelog:skip

#5231 Temporarily lower codecov threshold below 95%
  .codecov.yml
  plugin/storage/grpc/shared/grpc_handler_test.go
Labels: changelog:skip

#5152 [jaeger-v2] Add support for Elasticsearch
  cmd/jaeger/config-elasticsearch.yaml
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
  pkg/es/config/config.go
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
Labels: v2, changelog:exprimental

#5158 Add Elasticsearch storage support for adaptive sampling
  cmd/es-index-cleaner/app/index_filter.go
  cmd/es-index-cleaner/app/index_filter_test.go
  cmd/es-rollover/app/flags.go
  cmd/es-rollover/app/flags_test.go
  cmd/es-rollover/app/index_options.go
  cmd/es-rollover/app/index_options_test.go
  cmd/es-rollover/app/init/action.go
  cmd/es-rollover/app/init/flags.go
  cmd/es-rollover/app/init/flags_test.go
  cmd/es-rollover/app/lookback/action.go
  cmd/es-rollover/app/rollover/action.go
  cmd/esmapping-generator/app/renderer/render.go
  pkg/es/config/config.go
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
  plugin/storage/es/mappings/fixtures/jaeger-sampling-7.json
  plugin/storage/es/mappings/fixtures/jaeger-sampling-8.json
  plugin/storage/es/mappings/fixtures/jaeger-sampling.json
  plugin/storage/es/mappings/jaeger-sampling-7.json
  plugin/storage/es/mappings/jaeger-sampling-8.json
  plugin/storage/es/mappings/jaeger-sampling.json
  plugin/storage/es/mappings/mapping.go
  plugin/storage/es/mappings/mapping_test.go
  plugin/storage/es/options.go
  plugin/storage/es/samplingstore/dbmodel/converter.go
  plugin/storage/es/samplingstore/dbmodel/converter_test.go
  plugin/storage/es/samplingstore/dbmodel/model.go
  plugin/storage/es/samplingstore/storage.go
  plugin/storage/es/samplingstore/storage_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/es_index_cleaner_test.go
  plugin/storage/integration/es_index_rollover_test.go
Labels: changelog:exprimental
