Repository jaegertracing/jaeger, pull requests merged in 2024-12, with the labels that each got.

#6282 [cassandra] Change compaction window default to 2hrs
  pkg/cassandra/config/config.go
Labels: changelog:bugfix-or-minor-feature, storage/cassandra

#6284 Fix password in integration test
  plugin/storage/integration/cassandra_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature

#6287 [metrics][storage] Move metrics reader decorator to metrics storage factory
  cmd/all-in-one/main.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/query/main.go
  plugin/metrics/disabled/factory.go
  plugin/metrics/disabled/factory_test.go
  plugin/metrics/factory.go
  plugin/metrics/factory_test.go
  plugin/metrics/prometheus/factory.go
  plugin/metrics/prometheus/factory_test.go
  storage/factory.go
  storage/mocks/MetricsFactory.go
Labels: area/storage, changelog:breaking-change

#6289 [chore] Make package naming more consistent
  .mockery.yaml
  cmd/all-in-one/main.go
  cmd/anonymizer/app/query/query_test.go
  cmd/internal/env/command.go
  cmd/jaeger/internal/exporters/storageexporter/exporter_test.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/integration/storagecleaner/extension_test.go
  cmd/query/app/grpc_handler.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/query_parser.go
  cmd/query/app/querysvc/metrics_query_service.go
  cmd/query/main.go
  plugin/metricstore/disabled/factory.go
  plugin/metricstore/disabled/factory_test.go
  plugin/metricstore/disabled/package_test.go
  plugin/metricstore/disabled/reader.go
  plugin/metricstore/disabled/reader_test.go
  plugin/metricstore/factory.go
  plugin/metricstore/factory_config.go
  plugin/metricstore/factory_config_test.go
  plugin/metricstore/factory_test.go
  plugin/metricstore/package_test.go
  plugin/metricstore/prometheus/factory.go
  plugin/metricstore/prometheus/factory_test.go
  plugin/metricstore/prometheus/metricstore/dbmodel/to_domain.go
  plugin/metricstore/prometheus/metricstore/dbmodel/to_domain_test.go
  plugin/metricstore/prometheus/metricstore/reader.go
  plugin/metricstore/prometheus/metricstore/reader_test.go
  plugin/metricstore/prometheus/metricstore/testdata/empty_response.json
  plugin/metricstore/prometheus/metricstore/testdata/service_datapoint_response.json
  plugin/metricstore/prometheus/metricstore/testdata/service_span_name_datapoint_response.json
  plugin/metricstore/prometheus/metricstore/testdata/warning_response.json
  plugin/metricstore/prometheus/options.go
  storage/factory.go
  storage/metricstore/empty_test.go
  storage/metricstore/interface.go
  storage/metricstore/metricstoremetrics/decorator.go
  storage/metricstore/metricstoremetrics/decorator_test.go
  storage/metricstore/mocks/Reader.go
  storage/mocks/MetricsFactory.go
Labels: area/storage, changelog:bugfix-or-minor-feature

#6292 [chore] Rename `spanstore` to `tracestore` for v2 storage
  cmd/jaeger/internal/exporters/storageexporter/exporter.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  storage_v2/factoryadapter/factory.go
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
  storage_v2/factoryadapter/writer.go
  storage_v2/tracestore/empty_test.go
  storage_v2/tracestore/factory.go
  storage_v2/tracestore/reader.go
  storage_v2/tracestore/writer.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6296 [chore] Regenerate mocks after package rename
  cmd/jaeger/internal/exporters/storageexporter/exporter_test.go
  plugin/metricstore/factory_test.go
  storage/mocks/MetricStoreFactory.go
Labels: area/storage, changelog:skip

#6293 [chore] Return nil from storage factories when there is an error in creating span reader
  plugin/storage/cassandra/factory.go
  plugin/storage/cassandra/factory_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
Labels: area/storage, storage/elasticsearch, changelog:bugfix-or-minor-feature, storage/cassandra

#6170 [v2][storage] Implement read path for v2 storage interface
  .mockery.yaml
  cmd/all-in-one/main.go
  cmd/anonymizer/app/query/query_test.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
  cmd/query/app/server_test.go
  cmd/query/app/token_propagation_test.go
  cmd/query/main.go
  storage_v2/factoryadapter/factory_test.go
  storage_v2/tracestore/mocks/Factory.go
  storage_v2/tracestore/mocks/Reader.go
  storage_v2/tracestore/mocks/Writer.go
Labels: area/storage, changelog:new-feature, v2

#6322 Pring EOL notice from v1 binaries
  cmd/all-in-one/main.go
  cmd/collector/main.go
  cmd/ingester/main.go
  cmd/internal/flags/service.go
  cmd/query/main.go
Labels: changelog:bugfix-or-minor-feature

#6323 Add mahadzaryab1 to maintainers
  GOVERNANCE.md
  MAINTAINERS.md
  README.md
  RELEASE.md
Labels: changelog:skip, governance

#6310 Run e2e jobs as a single workflow
  .github/workflows/ci-e2e-all.yml
  .github/workflows/ci-e2e-badger.yaml
  .github/workflows/ci-e2e-cassandra.yml
  .github/workflows/ci-e2e-elasticsearch.yml
  .github/workflows/ci-e2e-grpc.yml
  .github/workflows/ci-e2e-kafka.yml
  .github/workflows/ci-e2e-memory.yaml
  .github/workflows/ci-e2e-opensearch.yml
Labels: changelog:ci

#6324 [fix] Fix call to `GetDependencies` in grpc handler
  cmd/query/app/grpc_handler.go
  cmd/query/app/grpc_handler_test.go
Labels: bug, changelog:bugfix-or-minor-feature

#6297 [v2][storage] Add dependency store to v2 storage interface
  .mockery.yaml
  cmd/all-in-one/main.go
  cmd/anonymizer/app/query/query_test.go
  cmd/jaeger/internal/exporters/storageexporter/exporter.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/handler_deps_test.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
  cmd/query/app/server_test.go
  cmd/query/main.go
  storage_v2/depstore/factory.go
  storage_v2/depstore/mocks/Factory.go
  storage_v2/depstore/mocks/Reader.go
  storage_v2/depstore/package_test.go
  storage_v2/depstore/reader.go
  storage_v2/factory.go
  storage_v2/factoryadapter/factory.go
  storage_v2/factoryadapter/factory_test.go
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
  storage_v2/tracestore/factory.go
  storage_v2/tracestore/mocks/Factory.go
Labels: area/storage, changelog:new-feature, v2

#6325 [v2][storage] Implement `GetServices` and `GetOperations` in v2 factory adapter
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6326 [storage][v2] Implement `FindTraceIDs` in v2 factory adapter
  model/ids.go
  model/ids_test.go
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6328 [storage][v2] Implement `FindTraces` in v2 factory adapter
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
  storage_v2/tracestore/reader.go
  storage_v2/tracestore/reader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6331 Add Comments for CompactionWindow Config Advice
  pkg/cassandra/config/config.go
Labels: storage/cassandra, changelog:skip

#6335 [fix] Fallback to system CA certs pool
  cmd/ingester/app/flags_test.go
  pkg/config/tlscfg/options.go
  pkg/kafka/auth/config_test.go
  plugin/storage/kafka/options_test.go
Labels: changelog:bugfix-or-minor-feature

#6336 Add go leak check to Cassandra and Kafka e2e tests
  pkg/testutils/leakcheck.go
  plugin/storage/integration/cassandra_test.go
  plugin/storage/integration/kafka_test.go
Labels: storage/kafka, storage/cassandra, changelog:test

#6277 [WIP][collector] Switch to OTEL's http/grpc server
  cmd/all-in-one/main.go
  cmd/collector/app/collector.go
  cmd/collector/app/collector_test.go
  cmd/collector/app/flags/flags.go
  cmd/collector/app/flags/flags_test.go
  cmd/collector/app/handler/otlp_receiver.go
  cmd/collector/app/handler/otlp_receiver_test.go
  cmd/collector/app/handler/zipkin_receiver.go
  cmd/collector/app/handler/zipkin_receiver_test.go
  cmd/collector/app/handler/zipkin_receiver_tls_test.go
  cmd/collector/app/server/grpc.go
  cmd/collector/app/server/grpc_test.go
  cmd/collector/app/server/http.go
  cmd/collector/app/server/http_test.go
  cmd/collector/main.go
  pkg/config/corscfg/flags.go
  pkg/config/corscfg/flags_test.go
  pkg/config/corscfg/options.go
  pkg/telemetry/settings.go
Labels: changelog:bugfix-or-minor-feature

#6319 [admin] Use OTEL helper instead of tlscfg
  cmd/internal/flags/admin.go
  cmd/internal/flags/admin_test.go
  cmd/internal/flags/service_test.go
Labels: changelog:bugfix-or-minor-feature

#6346 [v2][query] Add interface for adjuster to operate on OTLP data format
  cmd/query/app/querysvc/adjuster/adjuster.go
  cmd/query/app/querysvc/adjuster/adjuster_test.go
  cmd/query/app/querysvc/adjuster/package_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6347 Add Go Leak Check for Badgerstore, gRPC and Memstore e2e Tests
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/grpc_test.go
  plugin/storage/integration/memstore_test.go
Labels: changelog:bugfix-or-minor-feature, storage/badger

#6351 [remote-storage] Use OTEL helper instead of tlscfg
  cmd/remote-storage/app/flags.go
  cmd/remote-storage/app/flags_test.go
  cmd/remote-storage/app/server.go
  cmd/remote-storage/app/server_test.go
  cmd/remote-storage/main.go
  plugin/storage/integration/remote_memory_storage.go
Labels: area/storage, changelog:bugfix-or-minor-feature

#6354 [jaeger][v2] implement span links adjuster to operate on otlp data model
  cmd/query/app/querysvc/adjuster/spanlinks.go
  cmd/query/app/querysvc/adjuster/spanlinks_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6345 Remove TLS loading and replace with OTEL configtls
  cmd/agent/app/reporter/grpc/builder.go
  cmd/agent/app/reporter/grpc/builder_test.go
  cmd/agent/app/reporter/grpc/collector_proxy.go
  cmd/agent/app/reporter/grpc/flags.go
  cmd/agent/app/reporter/grpc/flags_test.go
  pkg/config/tlscfg/cert_watcher.go
  pkg/config/tlscfg/cert_watcher_test.go
  pkg/config/tlscfg/certpool_unix.go
  pkg/config/tlscfg/certpool_windows.go
  pkg/config/tlscfg/ciphersuites.go
  pkg/config/tlscfg/ciphersuites_test.go
  pkg/config/tlscfg/options.go
  pkg/config/tlscfg/options_test.go
Labels: changelog:bugfix-or-minor-feature

#6355 [v2][adjuster] Implement ip attribute adjuster to operate on otlp data model
  cmd/query/app/querysvc/adjuster/adjuster.go
  cmd/query/app/querysvc/adjuster/ipattribute.go
  cmd/query/app/querysvc/adjuster/ipattribute_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6357 Respond correctly to stream send error
  cmd/query/app/apiv3/grpc_handler.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/apiv3/otlp_translator.go
Labels: changelog:bugfix-or-minor-feature

#6359 Change Storage v2 API to use streaming
  cmd/query/app/querysvc/query_service_test.go
  pkg/iter/iter.go
  pkg/iter/iter_test.go
  pkg/iter/package_test.go
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
  storage_v2/tracestore/mocks/Reader.go
  storage_v2/tracestore/reader.go
Labels: area/storage, v2, changelog:exprimental

#6358 [v2][adjuster] Implement otel attribute adjuster to operate on otlp data model
  cmd/query/app/querysvc/adjuster/resourceattributes.go
  cmd/query/app/querysvc/adjuster/resourceattributes_test.go
  cmd/query/app/querysvc/adjuster/warning.go
  cmd/query/app/querysvc/adjuster/warning_test.go
Labels: changelog:bugfix-or-minor-feature, area/otel, v2

#6361 Change storage_v2 GetTrace to GetTraces plural
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
  storage_v2/tracestore/mocks/Reader.go
  storage_v2/tracestore/reader.go
  storage_v2/tracestore/reader_test.go
Labels: area/storage, v2, changelog:exprimental

#6242 [feat] Add time window for GetTrace in span store interface
  cmd/anonymizer/app/query/query.go
  cmd/anonymizer/app/query/query_test.go
  cmd/jaeger/internal/exporters/storageexporter/exporter_test.go
  cmd/jaeger/internal/integration/span_reader.go
  cmd/query/app/apiv3/gateway_test.go
  cmd/query/app/apiv3/grpc_handler.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/grpc_handler.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/handler_archive_test.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
  cmd/query/app/server_test.go
  plugin/storage/badger/spanstore/read_write_test.go
  plugin/storage/badger/spanstore/reader.go
  plugin/storage/badger/spanstore/rw_internal_test.go
  plugin/storage/blackhole/blackhole.go
  plugin/storage/blackhole/blackhole_test.go
  plugin/storage/cassandra/savetracetest/main.go
  plugin/storage/cassandra/spanstore/reader.go
  plugin/storage/cassandra/spanstore/reader_test.go
  plugin/storage/es/spanstore/reader.go
  plugin/storage/es/spanstore/reader_test.go
  plugin/storage/grpc/shared/archive.go
  plugin/storage/grpc/shared/archive_test.go
  plugin/storage/grpc/shared/grpc_client.go
  plugin/storage/grpc/shared/grpc_client_test.go
  plugin/storage/grpc/shared/grpc_handler.go
  plugin/storage/grpc/shared/grpc_handler_test.go
  plugin/storage/integration/integration.go
  plugin/storage/integration/kafka_test.go
  plugin/storage/memory/memory.go
  plugin/storage/memory/memory_test.go
  storage/spanstore/interface.go
  storage/spanstore/mocks/Reader.go
  storage/spanstore/spanstoremetrics/read_metrics.go
  storage/spanstore/spanstoremetrics/read_metrics_test.go
  storage_v2/factoryadapter/reader.go
  storage_v2/factoryadapter/reader_test.go
  storage_v2/factoryadapter/writer_test.go
Labels: enhancement, area/storage, storage/elasticsearch, changelog:new-feature, storage/badger, storage/cassandra

#6365 [refactor] Rename factoryadapter to v1adapter
  cmd/all-in-one/main.go
  cmd/anonymizer/app/query/query_test.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
  cmd/query/app/server_test.go
  cmd/query/app/token_propagation_test.go
  cmd/query/main.go
  storage_v2/v1adapter/README.md
  storage_v2/v1adapter/factory.go
  storage_v2/v1adapter/factory_test.go
  storage_v2/v1adapter/package_test.go
  storage_v2/v1adapter/reader.go
  storage_v2/v1adapter/reader_test.go
  storage_v2/v1adapter/writer.go
  storage_v2/v1adapter/writer_test.go
Labels: changelog:skip

#6362 [v2][adjuster] Rework adjuster interface and refactor adjusters to return implemented struct
  cmd/query/app/querysvc/adjuster/adjuster.go
  cmd/query/app/querysvc/adjuster/adjuster_test.go
  cmd/query/app/querysvc/adjuster/ipattribute.go
  cmd/query/app/querysvc/adjuster/ipattribute_test.go
  cmd/query/app/querysvc/adjuster/resourceattributes.go
  cmd/query/app/querysvc/adjuster/resourceattributes_test.go
  cmd/query/app/querysvc/adjuster/spanlinks.go
  cmd/query/app/querysvc/adjuster/spanlinks_test.go
  cmd/query/app/querysvc/adjuster/warning.go
  internal/jptrace/package_test.go
  internal/jptrace/warning.go
  internal/jptrace/warning_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6368 Feat: Add time window for GetTrace of anonymizer
  cmd/anonymizer/app/flags.go
  cmd/anonymizer/app/flags_test.go
  cmd/anonymizer/app/query/query.go
  cmd/anonymizer/app/query/query_test.go
  cmd/anonymizer/main.go
Labels: changelog:bugfix-or-minor-feature

#6375 [go.mod] Merge indirect groups into one
  go.mod
Labels: changelog:dependencies

#6381 [v2][adjuster] Add warning to span links adjuster
  cmd/query/app/querysvc/adjuster/spanlinks.go
  cmd/query/app/querysvc/adjuster/spanlinks_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6372 [api_v3] Add time window for GetTrace http_gateway
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/apiv3/http_gateway_test.go
Labels: changelog:bugfix-or-minor-feature

#6367 [v2][adjuster] Implement span ID uniquifier adjuster to operate on otlp data model
  cmd/query/app/querysvc/adjuster/adjuster.go
  cmd/query/app/querysvc/adjuster/ipattribute.go
  cmd/query/app/querysvc/adjuster/resourceattributes.go
  cmd/query/app/querysvc/adjuster/spaniduniquifier.go
  cmd/query/app/querysvc/adjuster/spaniduniquifier_test.go
  cmd/query/app/querysvc/adjuster/spanlinks.go
Labels: changelog:bugfix-or-minor-feature, v2

#6374 [fix][query] Filter out tracing for access to static UI assets
  cmd/query/app/server.go
  go.mod
  go.sum
Labels: changelog:bugfix-or-minor-feature

#6339 Add go leak checks to ES/OS tests
  pkg/testutils/leakcheck.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/es_index_cleaner_test.go
  plugin/storage/integration/es_index_rollover_test.go
  plugin/storage/integration/package_test.go
  scripts/check-goleak-files.sh
Labels: area/storage, storage/elasticsearch, changelog:test

#6383 [v2][adjuster] Remove error return from adjuster interface
  cmd/query/app/querysvc/adjuster/adjuster.go
  cmd/query/app/querysvc/adjuster/adjuster_test.go
  cmd/query/app/querysvc/adjuster/ipattribute.go
  cmd/query/app/querysvc/adjuster/ipattribute_test.go
  cmd/query/app/querysvc/adjuster/resourceattributes.go
  cmd/query/app/querysvc/adjuster/resourceattributes_test.go
  cmd/query/app/querysvc/adjuster/spaniduniquifier.go
  cmd/query/app/querysvc/adjuster/spaniduniquifier_test.go
  cmd/query/app/querysvc/adjuster/spanlinks.go
  cmd/query/app/querysvc/adjuster/spanlinks_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6360 Support extra custom query parameters in requests to Prometheus backend
  pkg/prometheus/config/config.go
  plugin/metricstore/prometheus/metricstore/reader.go
  plugin/metricstore/prometheus/metricstore/reader_test.go
Labels: enhancement, changelog:bugfix-or-minor-feature

#6386 Document maintainer actions
  MAINTAINERS.md
Labels: documentation, changelog:skip, governance

#6389 [v2][adjuster] Implement adjuster for sorting attributes and events
  cmd/query/app/querysvc/adjuster/sort.go
  cmd/query/app/querysvc/adjuster/sort_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6390 [refactor] Clean up span.kind tag handling
  cmd/agent/app/reporter/grpc/reporter_test.go
  cmd/anonymizer/app/anonymizer/anonymizer.go
  cmd/anonymizer/app/uiconv/extractor_test.go
  cmd/anonymizer/app/uiconv/module_test.go
  cmd/query/app/apiv3/gateway_test.go
  model/adjuster/span_hash_deduper_test.go
  model/adjuster/zipkin_span_id_uniquify_test.go
  model/converter/thrift/zipkin/to_domain.go
  model/converter/thrift/zipkin/to_domain_test.go
  model/keyvalue.go
  model/keyvalues_test.go
  model/span.go
  model/span_test.go
  plugin/storage/cassandra/spanstore/writer.go
  plugin/storage/cassandra/spanstore/writer_test.go
  plugin/storage/integration/integration.go
  plugin/storage/memory/memory.go
  plugin/storage/memory/memory_test.go
Labels: changelog:skip

#6159 Add optional time window for GetTrace & SearchTrace of http_handler
  cmd/query/app/handler_archive_test.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
Labels: enhancement, area/storage, changelog:bugfix-or-minor-feature

#6391 [v2][adjuster] Implement adjuster for deduplicating spans
  cmd/query/app/querysvc/adjuster/hash.go
  cmd/query/app/querysvc/adjuster/hash_test.go
  cmd/query/app/querysvc/adjuster/sort.go
Labels: changelog:bugfix-or-minor-feature, v2

#6392 [v2][adjuster] Implement adjuster for correct timestamps for clockskew
  cmd/query/app/querysvc/adjuster/clockskew.go
  cmd/query/app/querysvc/adjuster/clockskew_test.go
  pkg/otelsemconv/semconv.go
Labels: changelog:bugfix-or-minor-feature, v2

#6394 [v2][adjuster] Implement otlp to model translator with post processing
  .golangci.yml
  cmd/collector/app/handler/otlp_receiver.go
  cmd/jaeger/internal/processors/adaptivesampling/processor.go
  cmd/query/app/otlp_translator.go
  internal/jptrace/translator.go
  internal/jptrace/translator_test.go
  model/ids.go
  model/ids_test.go
  storage_v2/v1adapter/writer.go
Labels: changelog:bugfix-or-minor-feature, v2

#6396 [v2][adjuster] Implement function to get standard adjusters to operate on otlp format
  cmd/query/app/querysvc/adjuster/clockskew.go
  cmd/query/app/querysvc/adjuster/clockskew_test.go
  cmd/query/app/querysvc/adjuster/hash.go
  cmd/query/app/querysvc/adjuster/hash_test.go
  cmd/query/app/querysvc/adjuster/ipattribute.go
  cmd/query/app/querysvc/adjuster/ipattribute_test.go
  cmd/query/app/querysvc/adjuster/libraryattributes.go
  cmd/query/app/querysvc/adjuster/libraryattributes_test.go
  cmd/query/app/querysvc/adjuster/sort.go
  cmd/query/app/querysvc/adjuster/sort_test.go
  cmd/query/app/querysvc/adjuster/spaniduniquifier.go
  cmd/query/app/querysvc/adjuster/spaniduniquifier_test.go
  cmd/query/app/querysvc/adjuster/spanlinks.go
  cmd/query/app/querysvc/adjuster/spanlinks_test.go
  cmd/query/app/querysvc/adjuster/standard.go
  cmd/query/app/querysvc/adjuster/standard_test.go
Labels: changelog:bugfix-or-minor-feature, v2

#6316 Compatibility updates for v2 in README
  README.md
Labels: documentation, v2, changelog:skip

#6397 [v2][adjuster] Implement model to otlp translator with post processing
  .golangci.yml
  cmd/jaeger/internal/integration/span_writer.go
  cmd/query/app/apiv3/otlp_translator.go
  cmd/query/app/querysvc/adjuster/clockskew.go
  cmd/query/app/querysvc/adjuster/hash.go
  cmd/query/app/querysvc/adjuster/libraryattributes.go
  cmd/query/app/querysvc/adjuster/spaniduniquifier.go
  cmd/query/app/querysvc/adjuster/spanlinks.go
  internal/jptrace/translator.go
  internal/jptrace/translator_test.go
  internal/jptrace/warning.go
  internal/jptrace/warning_test.go
  storage_v2/v1adapter/reader.go
Labels: changelog:bugfix-or-minor-feature, v2

#6401 [v2][query] Implement helper to buffer sequence of traces
  internal/jptrace/aggregator.go
  internal/jptrace/aggregator_test.go
  storage_v2/tracestore/reader.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6403 [fix] Fix incorrect usage of iter package in aggregator
  .golangci.yml
  internal/jptrace/aggregator.go
Labels: changelog:bugfix-or-minor-feature

#6404 [fix] Fix test expectations for translator to avoid depending on order
  internal/jptrace/translator_test.go
Labels: bug, changelog:ci

#6400 Enhance Kafka integration tests to support multiple Kafka versions
  .github/workflows/ci-e2e-kafka.yml
  docker-compose/kafka/docker-compose.yml
  docker-compose/kafka/v2/docker-compose.yml
  docker-compose/kafka/v3/docker-compose.yml
  renovate.json
  scripts/kafka-integration-test.sh
Labels: storage/kafka, changelog:ci, docker

#6406 [refactor] Introduce helper for creating map of spans
  internal/jptrace/spanmap.go
  internal/jptrace/spanmap_test.go
  internal/jptrace/translator.go
  internal/jptrace/translator_test.go
Labels: changelog:bugfix-or-minor-feature

#6413 Enable UDP ports in all-in-one
  cmd/jaeger/internal/all-in-one.yaml
Labels: changelog:bugfix-or-minor-feature

#6414 [refactor] Move model<->otlp translation from `jptrace` to `v1adapter`
  .golangci.yml
  cmd/collector/app/handler/otlp_receiver.go
  cmd/jaeger/internal/integration/span_writer.go
  cmd/jaeger/internal/processors/adaptivesampling/processor.go
  cmd/query/app/apiv3/otlp_translator.go
  cmd/query/app/otlp_translator.go
  internal/jptrace/warning.go
  storage_v2/v1adapter/reader.go
  storage_v2/v1adapter/translator.go
  storage_v2/v1adapter/translator_test.go
  storage_v2/v1adapter/writer.go
Labels: changelog:bugfix-or-minor-feature

#6388 Upgrade storage integration test to v2 Trace Reader
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/jaeger/internal/integration/tailsampling_test.go
  plugin/storage/integration/badgerstore_test.go
  plugin/storage/integration/cassandra_test.go
  plugin/storage/integration/elasticsearch_test.go
  plugin/storage/integration/grpc_test.go
  plugin/storage/integration/integration.go
  plugin/storage/integration/kafka_test.go
  plugin/storage/integration/memstore_test.go
  storage_v2/v1adapter/translator.go
  storage_v2/v1adapter/translator_test.go
Labels: area/storage, v2, changelog:ci

#6419 Fix make proto to use gsed on MacOS
  Makefile
Labels: changelog:skip

#6421 Make api_v3 proto accessible from other packages
  Makefile.Protobuf.mk
  cmd/query/app/apiv3/gateway_test.go
  cmd/query/app/apiv3/grpc_handler.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/server.go
  internal/proto/api_v3/query_service.pb.go
  internal/proto/api_v3/traces.go
  internal/proto/api_v3/traces_test.go
Labels: changelog:skip

#6427 Do not test with Kafka 2.x
  .github/workflows/ci-e2e-kafka.yml
  docker-compose/kafka/v2/docker-compose.yml
  scripts/kafka-integration-test.sh
Labels: storage/kafka, changelog:ci, docker

#6428 [chore] Move es/spanstore/dbmodel to internal directory
  plugin/storage/es/spanstore/internal/dbmodel/fixtures/domain_01.json
  plugin/storage/es/spanstore/internal/dbmodel/fixtures/es_01.json
  plugin/storage/es/spanstore/internal/dbmodel/from_domain.go
  plugin/storage/es/spanstore/internal/dbmodel/from_domain_test.go
  plugin/storage/es/spanstore/internal/dbmodel/json_span_compare_test.go
  plugin/storage/es/spanstore/internal/dbmodel/model.go
  plugin/storage/es/spanstore/internal/dbmodel/package_test.go
  plugin/storage/es/spanstore/internal/dbmodel/to_domain.go
  plugin/storage/es/spanstore/internal/dbmodel/to_domain_test.go
  plugin/storage/es/spanstore/reader.go
  plugin/storage/es/spanstore/reader_test.go
  plugin/storage/es/spanstore/service_operation.go
  plugin/storage/es/spanstore/service_operation_test.go
  plugin/storage/es/spanstore/writer.go
  plugin/storage/es/spanstore/writer_test.go
Labels: area/storage, storage/elasticsearch, changelog:bugfix-or-minor-feature

#6426 [v1][adjuster] Change v1 adjuster interface to not return error and modify trace in place
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
  model/adjuster/adjuster.go
  model/adjuster/adjuster_test.go
  model/adjuster/bad_span_references.go
  model/adjuster/bad_span_references_test.go
  model/adjuster/clockskew.go
  model/adjuster/clockskew_test.go
  model/adjuster/ip_tag.go
  model/adjuster/ip_tag_test.go
  model/adjuster/otel_tag.go
  model/adjuster/otel_tag_test.go
  model/adjuster/parent_reference.go
  model/adjuster/parent_reference_test.go
  model/adjuster/sort_tags_and_log_fields.go
  model/adjuster/sort_tags_and_log_fields_test.go
  model/adjuster/span_hash_deduper.go
  model/adjuster/span_hash_deduper_test.go
  model/adjuster/zipkin_span_id_uniquify.go
  model/adjuster/zipkin_span_id_uniquify_test.go
  plugin/storage/memory/memory.go
Labels: changelog:bugfix-or-minor-feature

#6424 Replace APIv2 with APIv3 client in e2e tests
  Makefile.IntegrationTests.mk
  cmd/jaeger/config-kafka-ingester.yaml
  cmd/jaeger/internal/integration/binary.go
  cmd/jaeger/internal/integration/e2e_integration.go
  cmd/jaeger/internal/integration/span_reader.go
  cmd/jaeger/internal/integration/trace_reader.go
  plugin/storage/integration/integration.go
  plugin/storage/memory/factory.go
  scripts/kafka-integration-test.sh
Labels: area/storage, storage/kafka, changelog:ci

#6438 [refactor][query] Propagate `RawTraces` flag to query service
  cmd/query/app/apiv3/grpc_handler.go
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/grpc_handler.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/query_parser.go
  cmd/query/app/query_parser_test.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
Labels: changelog:bugfix-or-minor-feature

#6423 [query] Enable trace adjusters in api_v2 and api_v3 handlers
  cmd/query/app/apiv3/gateway_test.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/http_handler.go
  cmd/query/app/querysvc/query_service.go
  cmd/query/app/querysvc/query_service_test.go
Labels: changelog:breaking-change

#6407 [jptrace] Add SpanIter helper function
  internal/jptrace/spaniter.go
  internal/jptrace/spaniter_test.go
Labels: changelog:bugfix-or-minor-feature

#6440 Support sampling file reload interval
  cmd/jaeger/internal/all-in-one.yaml
  cmd/jaeger/internal/extension/remotesampling/config.go
  cmd/jaeger/internal/extension/remotesampling/config_test.go
  cmd/jaeger/internal/extension/remotesampling/extension.go
  plugin/sampling/strategyprovider/static/provider.go
Labels: changelog:bugfix-or-minor-feature, area/sampling, v2

#6446 Move build scripts under scripts/build/
  .github/workflows/ci-crossdock.yml
  .github/workflows/ci-docker-all-in-one.yml
  .github/workflows/ci-docker-build.yml
  .github/workflows/ci-docker-hotrod.yml
  .github/workflows/ci-lint-checks.yaml
  .github/workflows/ci-release.yml
  Makefile
  Makefile.BuildBinaries.mk
  scripts/build/build-all-in-one-image.sh
  scripts/build/build-crossdock.sh
  scripts/build/build-hotrod-image.sh
  scripts/build/build-upload-a-docker-image.sh
  scripts/build/build-upload-docker-images.sh
  scripts/build/clean-binaries.sh
  scripts/build/package-deploy.sh
  scripts/build/rebuild-ui.sh
  scripts/es-integration-test.sh
Labels: changelog:ci

#6450 [chore] Create v2 directory for querysvc package
  cmd/query/app/querysvc/v2/adjuster/adjuster.go
  cmd/query/app/querysvc/v2/adjuster/adjuster_test.go
  cmd/query/app/querysvc/v2/adjuster/clockskew.go
  cmd/query/app/querysvc/v2/adjuster/clockskew_test.go
  cmd/query/app/querysvc/v2/adjuster/hash.go
  cmd/query/app/querysvc/v2/adjuster/hash_test.go
  cmd/query/app/querysvc/v2/adjuster/ipattribute.go
  cmd/query/app/querysvc/v2/adjuster/ipattribute_test.go
  cmd/query/app/querysvc/v2/adjuster/libraryattributes.go
  cmd/query/app/querysvc/v2/adjuster/libraryattributes_test.go
  cmd/query/app/querysvc/v2/adjuster/package_test.go
  cmd/query/app/querysvc/v2/adjuster/sort.go
  cmd/query/app/querysvc/v2/adjuster/sort_test.go
  cmd/query/app/querysvc/v2/adjuster/spaniduniquifier.go
  cmd/query/app/querysvc/v2/adjuster/spaniduniquifier_test.go
  cmd/query/app/querysvc/v2/adjuster/spanlinks.go
  cmd/query/app/querysvc/v2/adjuster/spanlinks_test.go
  cmd/query/app/querysvc/v2/adjuster/standard.go
  cmd/query/app/querysvc/v2/adjuster/standard_test.go
Labels: v2, changelog:skip

#6451 Remove stale docs
  cmd/jaeger/internal/extension/jaegerstorage/README.md
Labels: documentation, changelog:skip

#6343 [v2][storage] Create v2 query service to operate on otlp data model
  cmd/jaeger/internal/integration/trace_reader.go
  cmd/query/app/querysvc/v2/querysvc/package_test.go
  cmd/query/app/querysvc/v2/querysvc/service.go
  cmd/query/app/querysvc/v2/querysvc/service_test.go
  plugin/storage/integration/integration.go
  storage_v2/tracestore/mocks/Reader.go
  storage_v2/tracestore/reader.go
  storage_v2/v1adapter/reader.go
  storage_v2/v1adapter/reader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6441 [sampling] Inherit default per-operation strategies
  cmd/jaeger/internal/all-in-one.yaml
  cmd/jaeger/internal/extension/remotesampling/config.go
  cmd/jaeger/internal/extension/remotesampling/extension.go
  go.mod
  plugin/sampling/strategyprovider/static/options.go
Labels: changelog:breaking-change, area/sampling
