Repository jaegertracing/jaeger, pull requests merged in 2024-10, with the labels that each got.

#6030 [grpc storage]: Propagate tenant to grpc backend
  plugin/storage/grpc/config.go
Labels: area/storage, changelog:bugfix-or-minor-feature

#6042 [jaeger-v2] Consolidate v1 and v2 Configurations for GRPC Storage
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
  plugin/storage/grpc/config.go
  plugin/storage/grpc/config_test.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/grpc/options.go
  plugin/storage/grpc/options_test.go
Labels: area/storage, v2, changelog:exprimental

#6053 [fix] Upgrade to otel-collector v0.111.0 and fix breaking changes
  cmd/collector/app/handler/otlp_receiver.go
  cmd/collector/app/handler/otlp_receiver_test.go
  cmd/collector/app/handler/zipkin_receiver.go
  cmd/collector/app/handler/zipkin_receiver_test.go
  cmd/jaeger/internal/extension/remotesampling/extension.go
  cmd/jaeger/internal/processors/adaptivesampling/factory.go
  go.mod
  go.sum
  plugin/storage/grpc/config.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/grpc/options.go
  plugin/storage/grpc/options_test.go
Labels: area/otel, changelog:dependencies

#6052 [ci] disable fail fast behaviour for ci workflows
  .github/workflows/ci-build-binaries.yml
  .github/workflows/ci-docker-all-in-one.yml
  .github/workflows/ci-e2e-badger.yaml
  .github/workflows/ci-e2e-cassandra.yml
  .github/workflows/ci-e2e-grpc.yml
  .github/workflows/ci-e2e-kafka.yml
  .github/workflows/ci-e2e-spm.yml
Labels: changelog:ci

#6066 [jaeger-v2] Add Attributes Processor to Binary
  cmd/jaeger/internal/components.go
  go.mod
  go.sum
Labels: v2, changelog:exprimental

#6061 [cassandra] Prevent fallback to old schema for operation names table in case of db issues
  plugin/storage/cassandra/factory.go
  plugin/storage/cassandra/savetracetest/main.go
  plugin/storage/cassandra/spanstore/operation_names.go
  plugin/storage/cassandra/spanstore/operation_names_test.go
  plugin/storage/cassandra/spanstore/reader.go
  plugin/storage/cassandra/spanstore/reader_test.go
  plugin/storage/cassandra/spanstore/writer.go
  plugin/storage/cassandra/spanstore/writer_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, storage/cassandra

#6060 [jaeger-v2] Refactor ElasticSearch/OpenSearch Storage Configurations
  cmd/es-rollover/app/init/action.go
  cmd/es-rollover/app/init/flags.go
  cmd/es-rollover/app/init/flags_test.go
  cmd/esmapping-generator/app/flags_test.go
  cmd/esmapping-generator/app/renderer/render.go
  cmd/jaeger/config-elasticsearch.yaml
  cmd/jaeger/config-opensearch.yaml
  pkg/es/config/config.go
  pkg/es/config/config_test.go
  plugin/storage/es/dependencystore/storage.go
  plugin/storage/es/dependencystore/storage_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/mappings/jaeger-dependencies-8.json
  plugin/storage/es/mappings/jaeger-sampling-8.json
  plugin/storage/es/mappings/jaeger-service-7.json
  plugin/storage/es/mappings/jaeger-service-8.json
  plugin/storage/es/mappings/jaeger-span-8.json
  plugin/storage/es/mappings/mapping.go
  plugin/storage/es/mappings/mapping_test.go
  plugin/storage/es/options.go
  plugin/storage/es/options_test.go
  plugin/storage/es/samplingstore/storage.go
  plugin/storage/es/samplingstore/storage_test.go
  plugin/storage/es/spanstore/reader.go
  plugin/storage/es/spanstore/reader_test.go
  plugin/storage/es/spanstore/writer.go
  plugin/storage/es/spanstore/writer_test.go
Labels: storage/elasticsearch, changelog:exprimental

#6077 [jaeger-v2] Implement empty service name sanitizer for OTLP
  cmd/jaeger/internal/exporters/storageexporter/exporter.go
  cmd/jaeger/internal/exporters/storageexporter/exporter_test.go
  cmd/jaeger/internal/sanitizer/emptyservicename.go
  cmd/jaeger/internal/sanitizer/emptyservicename_test.go
  cmd/jaeger/internal/sanitizer/package_test.go
  cmd/jaeger/internal/sanitizer/sanitizer.go
  cmd/jaeger/internal/sanitizer/sanitizer_test.go
Labels: v2, changelog:exprimental

#6080 [jaeger-v2] Enable queueing configuration in storage exporter
  cmd/jaeger/internal/exporters/storageexporter/config.go
  cmd/jaeger/internal/exporters/storageexporter/factory.go
Labels: area/storage, v2, changelog:exprimental

#6079 [jaeger-v2] Migrate ElasticSearch/OpenSearch to use OTEL's TLS configuration
  pkg/es/config/config.go
  pkg/es/config/config_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/options.go
  plugin/storage/es/options_test.go
Labels: area/storage, v2, changelog:exprimental

#6078 [jaeger-v2] Implement UTF-8 sanitizer for OTLP
  cmd/jaeger/internal/sanitizer/sanitizer.go
  cmd/jaeger/internal/sanitizer/sanitizer_test.go
  cmd/jaeger/internal/sanitizer/utf8.go
  cmd/jaeger/internal/sanitizer/utf8_test.go
Labels: v2, changelog:exprimental

#6081 Remove jaeger-agent from distributions
  Makefile.BuildBinaries.mk
  Makefile.Windows.mk
  cmd/agent/app/builder.go
  cmd/agent/app/flags.go
  cmd/agent/app/ports.go
  cmd/agent/main.go
  cmd/all-in-one/Dockerfile
  cmd/all-in-one/all_in_one_test.go
  cmd/all-in-one/main.go
  cmd/collector/main.go
  cmd/jaeger/Dockerfile
  cmd/jaeger/internal/extension/remotesampling/extension.go
  cmd/jaeger/internal/extension/remotesampling/factory.go
  crossdock/docker-compose.yml
  crossdock/jaeger-docker-compose.yml
  docker-compose/jaeger-docker-compose.yml
  docker-compose/kafka/docker-compose.yml
  ports/ports.go
  scripts/build-all-in-one-image.sh
  scripts/build-upload-docker-images.sh
  scripts/generate-help-output.sh
  scripts/package-deploy.sh
Labels: changelog:breaking-change, docker

#6095 [fix][jaeger-v2] Fix non-determinstic test in utf-8 sanitizer
  cmd/jaeger/internal/sanitizer/utf8_test.go
Labels: bug, changelog:test

#6085 Use OTEL component host instead of no op host for prod code
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
Labels: changelog:bugfix-or-minor-feature

#6098 Fix rebuild-ui.sh script
  scripts/rebuild-ui.sh
Labels: ui, changelog:bugfix-or-minor-feature

#6091 [refractor] Switch to enums for ES mappings
  cmd/es-rollover/app/init/action.go
  cmd/esmapping-generator/app/renderer/render.go
  cmd/esmapping-generator/app/renderer/render_test.go
  cmd/esmapping-generator/main.go
  plugin/storage/es/mappings/mapping.go
  plugin/storage/es/mappings/mapping_test.go
Labels: enhancement, area/storage, changelog:bugfix-or-minor-feature

#6090 [jaeger-v2] Refactor ElasticSearch/OpenSearch configurations to have more logical groupings
  cmd/query/app/token_propagation_test.go
  pkg/es/config/config.go
  pkg/es/config/config_test.go
  plugin/storage/es/factory.go
  plugin/storage/es/factory_test.go
  plugin/storage/es/options.go
  plugin/storage/es/options_test.go
Labels: storage/elasticsearch, v2, changelog:exprimental

#6103 [chore][docs] Add documentation to ElasticSearch configuration
  pkg/es/config/config.go
Labels: documentation, storage/elasticsearch, changelog:exprimental

#6100 Update maintainer nomination process
  GOVERNANCE.md
Labels: changelog:skip

#6110 [v2] Add ES config comments
  pkg/es/config/config.go
Labels: storage/elasticsearch, v2, changelog:exprimental

#5935 Add OTLP JSON support for Kafka e2e Integration tests
  cmd/jaeger/internal/integration/kafka_test.go
Labels: storage/kafka, changelog:exprimental

#6102 Enable Lint Rule: import-shadowing
  .golangci.yml
  cmd/agent/app/agent.go
  cmd/agent/app/builder.go
  cmd/agent/app/processors/thrift_processor_test.go
  cmd/agent/app/reporter/client_metrics.go
  cmd/agent/app/reporter/flags.go
  cmd/collector/app/flags/flags.go
  cmd/collector/app/handler/grpc_handler_test.go
  cmd/collector/app/options.go
  cmd/collector/app/sanitizer/service_name_sanitizer.go
  cmd/ingester/app/builder/builder.go
  cmd/ingester/app/consumer/committing_processor.go
  cmd/ingester/app/consumer/consumer_test.go
  cmd/ingester/app/consumer/processor_factory.go
  cmd/ingester/app/processor/decorator/retry.go
  cmd/jaeger/internal/exporters/storageexporter/exporter_test.go
  cmd/jaeger/internal/extension/jaegerquery/factory_test.go
  cmd/jaeger/internal/integration/span_writer.go
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  crossdock/services/query.go
  examples/hotrod/services/frontend/best_eta.go
  examples/hotrod/services/route/client.go
  internal/metrics/otelmetrics/factory_test.go
  model/adjuster/span_hash_deduper_test.go
  model/adjuster/zipkin_span_id_uniquify_test.go
  model/converter/json/sampling_test.go
  model/converter/thrift/zipkin/to_domain.go
  model/converter/thrift/zipkin/to_domain_test.go
  pkg/clientcfg/clientcfghttp/handler.go
  pkg/clientcfg/clientcfghttp/handler_test.go
  pkg/fswatcher/fswatcher.go
  pkg/gzipfs/gzip.go
  pkg/version/handler.go
  plugin/metrics/prometheus/metricsstore/reader_test.go
  plugin/sampling/strategyprovider/adaptive/aggregator.go
  plugin/sampling/strategyprovider/static/provider.go
  plugin/sampling/strategyprovider/static/provider_test.go
  plugin/storage/badger/factory_test.go
  plugin/storage/badger/spanstore/rw_internal_test.go
  plugin/storage/cassandra/factory.go
  plugin/storage/cassandra/spanstore/reader.go
  plugin/storage/es/options.go
  plugin/storage/es/spanstore/reader.go
  plugin/storage/es/spanstore/service_operation.go
  plugin/storage/integration/integration.go
Labels: changelog:bugfix-or-minor-feature

#6055 [query] Use OTEL's helpers for grpc server
  cmd/all-in-one/main.go
  cmd/jaeger/internal/extension/jaegerquery/factory.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/query/app/flags.go
  cmd/query/app/flags_test.go
  cmd/query/app/server.go
  cmd/query/app/server_test.go
  cmd/query/app/token_propagation_test.go
  cmd/query/main.go
  pkg/telemetery/settings.go
Labels: changelog:bugfix-or-minor-feature, area/otel

#6120 [fix][query] Correct query server legacy condition
  cmd/query/app/server.go
Labels: bug, changelog:bugfix-or-minor-feature, v2

#6063 Use GRPC interceptors for bearer token
  cmd/query/app/server.go
  cmd/remote-storage/app/server.go
  pkg/bearertoken/grpc.go
  pkg/bearertoken/grpc_test.go
  plugin/storage/grpc/factory.go
Labels: changelog:bugfix-or-minor-feature

#6118 feat: automatically publish readme to docker hub
  scripts/build-upload-a-docker-image.sh
  scripts/upload-docker-readme.sh
  scripts/upload-docker-readme.test.sh
Labels: changelog:bugfix-or-minor-feature, docker

#6126 [fix] Remove command echoing
  scripts/upload-docker-readme.sh
  scripts/upload-docker-readme.test.sh
Labels: changelog:skip

#6125 [fix][grpc] Disable tracing in grpc storage writer clients
  cmd/jaeger/internal/integration/grpc_test.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/factory_test.go
  plugin/storage/grpc/shared/grpc_client.go
  plugin/storage/grpc/shared/grpc_client_test.go
Labels: bug, area/storage, changelog:bugfix-or-minor-feature

#6128 Move all query service HTTP handlers into one function
  cmd/query/app/apiv3/gateway_test.go
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/server.go
Labels: changelog:bugfix-or-minor-feature

#6116 Fix span deduplication via correct ordering of adjusters
  cmd/query/app/http_handler_test.go
  cmd/query/app/querysvc/adjusters.go
Labels: bug, changelog:bugfix-or-minor-feature

#6130 [agent] Add deprecation notice to the readme
  cmd/agent/README.md
Labels: changelog:skip

#6131 [query][test] Add unit test for tracing http requests in query server
  cmd/query/app/server_test.go
Labels: changelog:test

#6136 chore: fix function name in comment
  plugin/sampling/strategyprovider/static/factory.go
Labels: changelog:skip

#6133 Use GRPC interceptors instead of explicit context wrappers
  cmd/query/app/server.go
  plugin/metrics/prometheus/metricsstore/reader.go
  plugin/storage/grpc/factory.go
  plugin/storage/grpc/shared/archive.go
  plugin/storage/grpc/shared/grpc_client.go
  plugin/storage/grpc/shared/grpc_client_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature

#6121 [query] Use OTEL's helpers for http server
  cmd/query/app/apiv3/http_gateway.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/server.go
Labels: changelog:bugfix-or-minor-feature, area/otel

#6138 [jaeger-v2] Add HotROD integration test for jaeger-v2
  .github/workflows/ci-docker-hotrod.yml
  scripts/build-hotrod-image.sh
Labels: changelog:bugfix-or-minor-feature, v2

#6145 [fix][query] Remove bifurcation for grpc query server
  cmd/query/app/server.go
Labels: changelog:bugfix-or-minor-feature
