Repository jaegertracing/jaeger, pull requests merged in 2025-08, with the labels that each got.

#7399 Add `/deep-dependencies` endpoint
  cmd/query/app/ddg/deep_dependencies.go
  cmd/query/app/ddg/deep_dependencies_test.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
Labels: changelog:bugfix-or-minor-feature, go

#7419 Added TLS/SSL certification and automation for Jaeger Demo Deployment
  examples/oci/README.md
  examples/oci/ingress.yaml
  examples/oci/tls-cert/issuer.yaml
Labels: security, changelog:exprimental

#7421 Prepare Release v1.72.0 / v2.9.0
  CHANGELOG.md
  RELEASE.md
Labels: changelog:skip

#7426 Unpin github.com/ebitengine/purego
  go.mod
Labels: changelog:dependencies, go

#7427 Multiple minor changes in Jaeger demo deployment in OKE
  examples/oci/deploy-all.sh
  examples/oci/jaeger-values.yaml
  examples/oci/prometheus-svc.yaml
Labels: changelog:exprimental

#7429 Redirect to demo documentation in Jaeger demo deployment
  examples/oci/README.md
  examples/oci/config.yaml
  examples/oci/deploy-all.sh
  examples/oci/ingress.yaml
  examples/oci/jaeger-values.yaml
Labels: documentation, changelog:exprimental

#7438 chore: enable rangeValCopy from go-critic
  .golangci.yml
  cmd/anonymizer/main.go
  internal/storage/v1/grpc/shared/grpc_client.go
  internal/storage/v2/clickhouse/tracestore/dbmodel/to_dbmodel.go
Labels: area/storage, changelog:refactoring

#7414 [CI] Add new post comment workflow
  .github/workflows/ci-comment.yml
  .github/workflows/ci-e2e-all.yml
  scripts/e2e/metrics_summary.py
Labels: changelog:ci

#7448 [CI] Add upload pr_number artifacts action to ci-e2e-all.yml
  .github/workflows/ci-comment.yml
  .github/workflows/ci-e2e-all.yml
Labels: changelog:ci

#7440 Separate scripts for deployment upgrade and clean install of Jaeger Demo deployment and enable G-Tracking in Jaeger UI
  .github/workflows/ci-deploy-demo.yml
  examples/oci/config.yaml
  examples/oci/deploy-all.sh
  examples/oci/ui-config.json
Labels: ui, changelog:exprimental

#7451 Bump fossa action version to v3.0.1
  .github/workflows/fossa.yml
Labels: changelog:dependencies

#7462 [CI] Improve summary comment
  scripts/e2e/metrics_summary.py
Labels: changelog:ci

#7482 [ci] Sanitize transient metric labels before comparison
  scripts/e2e/compare_metrics.py
Labels: enhancement, storage/kafka, changelog:ci

#7481 chore(jaeger-tracegen): upgrade tracegen docker compose to jaeger-v2
  cmd/tracegen/docker-compose.yml
Labels: changelog:bugfix-or-minor-feature, docker

#7484 [chore]: Improve test coverage of expvar extension
  cmd/jaeger/internal/extension/expvar/extension.go
Labels: changelog:test
