Repository jaegertracing/jaeger, pull requests merged in 2025-03, with the labels that each got.

#6799 Use empty slices instead of nil
  internal/storage/v2/v1adapter/spanreader_test.go
  internal/storage/v2/v1adapter/translator.go
  internal/storage/v2/v1adapter/translator_test.go
Labels: enhancement, area/storage, changelog:bugfix-or-minor-feature

#6809 [refactor] Move internal `TracesData` type to package `jptrace`
  cmd/jaeger/internal/integration/trace_reader.go
  cmd/query/app/apiv3/grpc_handler.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/apiv3/http_gateway.go
  internal/jptrace/traces.go
  internal/jptrace/traces_test.go
  internal/proto/api_v3/query_service.pb.go
  scripts/makefiles/Protobuf.mk
Labels: area/storage, changelog:bugfix-or-minor-feature

#6796 [es] Refactor the ES SpanWriter to make it reusable for v2 APIs
  internal/storage/v1/elasticsearch/factory.go
  internal/storage/v1/elasticsearch/spanstore/service_operation_test.go
  internal/storage/v1/elasticsearch/spanstore/writer.go
  internal/storage/v1/elasticsearch/spanstore/writer_test.go
Labels: area/storage, storage/elasticsearch, changelog:bugfix-or-minor-feature, v2

#6819 [chore] Remove gogoproto annotations from `trace_storage.proto` and `dependency_storage.proto`
  internal/storage/v2/grpc/dependency_storage.proto
  internal/storage/v2/grpc/trace_storage.proto
  proto-gen/patch.sed
  proto-gen/storage/v2/dependency_storage.pb.go
  proto-gen/storage/v2/trace_storage.pb.go
  scripts/makefiles/Protobuf.mk
Labels: area/storage, changelog:bugfix-or-minor-feature

#6790 [fix] Allow es-index-cleaner to delete indices based on current time
  cmd/es-index-cleaner/app/cutoff_time.go
  cmd/es-index-cleaner/app/cutoff_time_test.go
  cmd/es-index-cleaner/main.go
Labels: area/storage, changelog:bugfix-or-minor-feature

#6828 [ES] Refactor the `GetOperations` and `GetServices` of SpanReader to make them reusable for v2 APIs
  .mockery.yaml
  internal/storage/v1/elasticsearch/factory.go
  internal/storage/v1/elasticsearch/spanstore/core_span_reader.go
  internal/storage/v1/elasticsearch/spanstore/internal/dbmodel/model.go
  internal/storage/v1/elasticsearch/spanstore/mocks/CoreSpanReader.go
  internal/storage/v1/elasticsearch/spanstore/reader.go
  internal/storage/v1/elasticsearch/spanstore/reader_test.go
  internal/storage/v1/elasticsearch/spanstore/readerv1.go
  internal/storage/v1/elasticsearch/spanstore/readerv1_test.go
  internal/storage/v1/elasticsearch/spanstore/service_operation_test.go
Labels: area/storage, storage/elasticsearch, v2, changelog:refactoring

#6830 [refactor] Return chunk of traces from remote storage api v2
  internal/storage/v2/grpc/trace_storage.proto
  proto-gen/storage/v2/trace_storage.pb.go
Labels: area/storage, v2, changelog:exprimental

#6691 Create a template/checklist for Jaeger release
  RELEASE.md
  scripts/release/formatter.py
  scripts/release/start.sh
Labels: changelog:skip

#6837 feat[dependabot]: clean up dependabot config
  .github/dependabot.yml
Labels: changelog:dependencies

#6829 [grpc][v2] Implement `GetServices` Call in GRPC reader for remote storage api v2
  internal/storage/v2/grpc/package_test.go
  internal/storage/v2/grpc/tracereader.go
  internal/storage/v2/grpc/tracereader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6844 remove ci-lint-dependabot-config.yml
  .github/workflows/ci-lint-dependabot-config.yml
Labels: changelog:skip

#6849 Make dco check email case-insensitive
  scripts/lint/dco_check.py
Labels: changelog:skip

#6848 [ES] Add feature to stop Legacy Trace IDs handling in SpanReader
  cmd/collector/main.go
  cmd/es-index-cleaner/app/flags.go
  cmd/es-index-cleaner/main.go
  cmd/ingester/main.go
  cmd/internal/featuregate/command.go
  cmd/internal/featuregate/command_test.go
  cmd/internal/featuregate/package_test.go
  cmd/internal/flags/service.go
  cmd/query/main.go
  cmd/remote-storage/main.go
  internal/storage/v1/elasticsearch/spanstore/reader.go
  internal/storage/v1/elasticsearch/spanstore/reader_test.go
Labels: storage/elasticsearch, changelog:bugfix-or-minor-feature

#6851 [agent] Remove unnecessary Server interface
  cmd/agent/app/servers/server.go
Labels: changelog:refactoring

#6843 [grpc][v2] Implement `GetOperations` Call in gRPC reader for remote storage api v2
  internal/storage/v2/grpc/tracereader.go
  internal/storage/v2/grpc/tracereader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6852 [agent] Refactor UDP server
  cmd/agent/app/builder.go
  cmd/agent/app/processors/thrift_processor.go
  cmd/agent/app/processors/thrift_processor_test.go
  cmd/agent/app/servers/package_test.go
  cmd/agent/app/servers/server.go
  cmd/agent/app/servers/server_test.go
  cmd/agent/app/servers/thriftudp/transport_test.go
  cmd/agent/app/servers/udpserver.go
  cmd/agent/app/servers/udpserver_test.go
Labels: changelog:refactoring

#6860 Instruct Renovate to pin GitHub Action hashes
  renovate.json
Labels: changelog:ci

#6863 [refactor] Move interface to remove cmd/agent dependency
  internal/sampling/http/handler.go
Labels: changelog:refactoring

#6845 [ES] Refactor `FindTraces` and `GetTrace` of SpanReader to make them reusable for v2 APIs
  internal/storage/v1/elasticsearch/spanstore/core_span_reader.go
  internal/storage/v1/elasticsearch/spanstore/internal/dbmodel/dot_replacer.go
  internal/storage/v1/elasticsearch/spanstore/internal/dbmodel/model.go
  internal/storage/v1/elasticsearch/spanstore/internal/dbmodel/to_domain.go
  internal/storage/v1/elasticsearch/spanstore/internal/dbmodel/to_domain_test.go
  internal/storage/v1/elasticsearch/spanstore/mocks/CoreSpanReader.go
  internal/storage/v1/elasticsearch/spanstore/reader.go
  internal/storage/v1/elasticsearch/spanstore/reader_test.go
  internal/storage/v1/elasticsearch/spanstore/readerv1.go
  internal/storage/v1/elasticsearch/spanstore/readerv1_test.go
Labels: storage/elasticsearch, changelog:bugfix-or-minor-feature, v2

#6868 🪦 Remove Agent code
  cmd/agent/Dockerfile
  cmd/agent/README.md
  cmd/agent/app/agent.go
  cmd/agent/app/agent_test.go
  cmd/agent/app/builder.go
  cmd/agent/app/builder_test.go
  cmd/agent/app/configmanager/grpc/manager.go
  cmd/agent/app/configmanager/grpc/manager_test.go
  cmd/agent/app/configmanager/manager.go
  cmd/agent/app/configmanager/metrics.go
  cmd/agent/app/configmanager/metrics_test.go
  cmd/agent/app/customtransport/buffered_read_transport.go
  cmd/agent/app/customtransport/buffered_read_transport_test.go
  cmd/agent/app/flags.go
  cmd/agent/app/flags_test.go
  cmd/agent/app/httpserver/srv.go
  cmd/agent/app/httpserver/srv_test.go
  cmd/agent/app/package_test.go
  cmd/agent/app/ports.go
  cmd/agent/app/processors/package_test.go
  cmd/agent/app/processors/processor.go
  cmd/agent/app/processors/thrift_processor.go
  cmd/agent/app/processors/thrift_processor_test.go
  cmd/agent/app/proxy_builders.go
  cmd/agent/app/reporter/client_metrics.go
  cmd/agent/app/reporter/client_metrics_test.go
  cmd/agent/app/reporter/connect_metrics.go
  cmd/agent/app/reporter/connect_metrics_test.go
  cmd/agent/app/reporter/flags.go
  cmd/agent/app/reporter/flags_test.go
  cmd/agent/app/reporter/grpc/builder.go
  cmd/agent/app/reporter/grpc/builder_test.go
  cmd/agent/app/reporter/grpc/collector_proxy.go
  cmd/agent/app/reporter/grpc/collector_proxy_test.go
  cmd/agent/app/reporter/grpc/flags.go
  cmd/agent/app/reporter/grpc/flags_test.go
  cmd/agent/app/reporter/grpc/package_test.go
  cmd/agent/app/reporter/grpc/reporter.go
  cmd/agent/app/reporter/grpc/reporter_test.go
  cmd/agent/app/reporter/metrics.go
  cmd/agent/app/reporter/metrics_test.go
  cmd/agent/app/reporter/package_test.go
  cmd/agent/app/reporter/reporter.go
  cmd/agent/app/reporter/reporter_test.go
  cmd/agent/app/servers/package_test.go
  cmd/agent/app/servers/thriftudp/socket_buffer.go
  cmd/agent/app/servers/thriftudp/socket_buffer_windows.go
  cmd/agent/app/servers/thriftudp/transport.go
  cmd/agent/app/servers/thriftudp/transport_test.go
  cmd/agent/app/servers/udpserver.go
  cmd/agent/app/servers/udpserver_test.go
  cmd/agent/app/testutils/in_memory_reporter.go
  cmd/agent/app/testutils/in_memory_reporter_test.go
  cmd/agent/app/testutils/mock_grpc_collector.go
  cmd/agent/app/testutils/package_test.go
  cmd/agent/app/testutils/thriftudp_client.go
  cmd/agent/app/testutils/thriftudp_client_test.go
  cmd/agent/main.go
Labels: changelog:bugfix-or-minor-feature

#6874 [ES] Remove pointer signatures from `CoreSpanReader`
  internal/storage/v1/elasticsearch/spanstore/core_span_reader.go
  internal/storage/v1/elasticsearch/spanstore/internal/dbmodel/model.go
  internal/storage/v1/elasticsearch/spanstore/mocks/CoreSpanReader.go
  internal/storage/v1/elasticsearch/spanstore/reader.go
  internal/storage/v1/elasticsearch/spanstore/reader_test.go
  internal/storage/v1/elasticsearch/spanstore/readerv1.go
  internal/storage/v1/elasticsearch/spanstore/readerv1_test.go
Labels: storage/elasticsearch, changelog:refactoring

#6875 Cleanup legacy models
  model/dependencies.go
  model/dependencies_test.go
  model/flags.go
  model/flags_test.go
  model/hash.go
  model/hash_test.go
  model/ids.go
  model/ids_proto_test.go
  model/ids_test.go
  model/keyvalue.go
  model/keyvalue_test.go
  model/keyvalues_test.go
  model/model.go
  model/package_test.go
  model/process.go
  model/process_test.go
  model/sort.go
  model/sort_test.go
  model/span.go
  model/span_test.go
  model/spanref.go
  model/spanref_test.go
  model/time.go
  model/time_test.go
  model/trace_test.go
  proto-gen/api_v2/collector.go
  proto-gen/api_v2/query.go
  proto-gen/api_v2/sampling.go
  thrift-gen/agent/agent.go
  thrift-gen/jaeger/jaeger.go
  thrift-gen/sampling/sampling.go
  thrift-gen/zipkincore/zipkincore.go
Labels: changelog:bugfix-or-minor-feature

#6879 Replace the use of model/converter/thrift/zipkin
  cmd/collector/app/handler/thrift_span_handler.go
  cmd/collector/app/handler/zipkin_receiver_test.go
  go.mod
  go.sum
  internal/storage/v1/kafka/marshalling_test.go
  internal/storage/v1/kafka/unmarshaller.go
  model/converter/thrift/zipkin/deserialize.go
  model/converter/thrift/zipkin/deserialize_test.go
  model/converter/thrift/zipkin/doc.go
  model/converter/thrift/zipkin/fixtures/domain_01.json
  model/converter/thrift/zipkin/fixtures/domain_02.json
  model/converter/thrift/zipkin/fixtures/domain_03.json
  model/converter/thrift/zipkin/fixtures/zipkin_01.json
  model/converter/thrift/zipkin/fixtures/zipkin_02.json
  model/converter/thrift/zipkin/fixtures/zipkin_03.json
  model/converter/thrift/zipkin/package_test.go
  model/converter/thrift/zipkin/process_hashtable.go
  model/converter/thrift/zipkin/process_hashtable_test.go
  model/converter/thrift/zipkin/to_domain.go
  model/converter/thrift/zipkin/to_domain_test.go
Labels: changelog:refactoring

#6882 [all-in-one] Avoid multi-arch builds in merge queue (#6880)
  .github/workflows/ci-docker-all-in-one.yml
Labels: changelog:ci, docker

#6858 [grpc][v2] Implement `FindTraceIDs` Call in gRPC reader for remote storage api v2
  internal/storage/v2/api/tracestore/reader.go
  internal/storage/v2/grpc/tracereader.go
  internal/storage/v2/grpc/tracereader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6877 Move pkg/normalizer to collector
  cmd/collector/app/metrics.go
  cmd/collector/app/normalize.go
  cmd/collector/app/normalize_test.go
  pkg/normalizer/service_name_test.go
Labels: changelog:refactoring

#6889 Move pkg/tenancy to internal/tenancy
  cmd/all-in-one/main.go
  cmd/collector/app/collector.go
  cmd/collector/app/collector_test.go
  cmd/collector/app/flags/flags.go
  cmd/collector/app/handler/grpc_handler.go
  cmd/collector/app/handler/grpc_handler_test.go
  cmd/collector/app/handler/otlp_receiver.go
  cmd/collector/app/handler/otlp_receiver_test.go
  cmd/collector/app/handler/zipkin_receiver.go
  cmd/collector/app/handler/zipkin_receiver_test.go
  cmd/collector/app/handler/zipkin_receiver_tls_test.go
  cmd/collector/app/server/grpc_test.go
  cmd/collector/app/span_handler_builder.go
  cmd/collector/app/span_handler_builder_test.go
  cmd/collector/app/span_processor.go
  cmd/collector/app/span_processor_test.go
  cmd/collector/main.go
  cmd/internal/printconfig/command_test.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/query/app/flags.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/server.go
  cmd/query/app/server_test.go
  cmd/query/app/token_propagation_test.go
  cmd/query/main.go
  cmd/remote-storage/app/flags.go
  cmd/remote-storage/app/server.go
  cmd/remote-storage/app/server_test.go
  cmd/remote-storage/main.go
  internal/storage/integration/remote_memory_storage.go
  internal/storage/v1/grpc/config.go
  internal/storage/v1/grpc/factory.go
  internal/storage/v1/grpc/factory_test.go
  internal/storage/v1/grpc/options.go
  internal/storage/v1/grpc/options_test.go
  internal/storage/v1/memory/memory.go
  internal/storage/v1/memory/memory_test.go
  internal/tenancy/context.go
  internal/tenancy/context_test.go
  internal/tenancy/flags.go
  internal/tenancy/flags_test.go
  internal/tenancy/grpc.go
  internal/tenancy/grpc_test.go
  internal/tenancy/http.go
  internal/tenancy/http_test.go
  internal/tenancy/manage_test.go
  internal/tenancy/manager.go
  internal/tenancy/package_test.go
Labels: changelog:refactoring

#6887 Move pkg/recoveryhandler to internal/recoveryhandler
  .gitignore
  cmd/collector/app/server/http.go
  cmd/internal/flags/admin.go
  cmd/query/app/server.go
  internal/recoveryhandler/zap.go
  internal/recoveryhandler/zap_test.go
Labels: changelog:refactoring

#6886 Move pkg/hostname to internal/hostname
  internal/hostname/hostname.go
  internal/hostname/hostname_test.go
  internal/sampling/samplingstrategy/adaptive/aggregator.go
  internal/storage/v1/cassandra/factory.go
Labels: changelog:refactoring

#6888 Move pkg/healthcheck to internal/healthcheck
  cmd/collector/app/collector.go
  cmd/collector/app/collector_test.go
  cmd/collector/app/server/http.go
  cmd/collector/app/server/http_test.go
  cmd/internal/flags/admin.go
  cmd/internal/flags/admin_test.go
  cmd/internal/flags/service.go
  cmd/internal/flags/service_test.go
  cmd/query/app/server_test.go
  cmd/remote-storage/app/server_test.go
  internal/healthcheck/handler.go
  internal/healthcheck/handler_test.go
  internal/healthcheck/internal_test.go
  internal/healthcheck/package_test.go
  internal/storage/integration/remote_memory_storage.go
  pkg/telemetry/settings.go
  pkg/telemetry/settings_test.go
Labels: changelog:refactoring

#6872 Remove sampling.strategies.bugfix-5270 flag and mark feature Stable
  cmd/jaeger/internal/extension/remotesampling/config.go
  cmd/jaeger/internal/extension/remotesampling/extension.go
  internal/sampling/samplingstrategy/file/options.go
  internal/sampling/samplingstrategy/file/provider.go
  internal/sampling/samplingstrategy/file/provider_test.go
Labels: changelog:breaking-change, area/sampling

#6883 [ES] Separate the `CoreSpanWriter` from `SpanWriter`
  .mockery.yaml
  internal/storage/v1/elasticsearch/spanstore/internal/dbmodel/from_domain_test.go
  internal/storage/v1/elasticsearch/spanstore/mocks/CoreSpanWriter.go
  internal/storage/v1/elasticsearch/spanstore/service_operation_test.go
  internal/storage/v1/elasticsearch/spanstore/writer.go
  internal/storage/v1/elasticsearch/spanstore/writer_test.go
  internal/storage/v1/elasticsearch/spanstore/writerv1.go
  internal/storage/v1/elasticsearch/spanstore/writerv1_test.go
Labels: storage/elasticsearch, v2, changelog:refactoring

#6895 Move pkg/fswatcher to internal/fswatcher
  cmd/query/app/static_handler.go
  cmd/query/app/static_handler_test.go
  internal/fswatcher/fswatcher.go
  internal/fswatcher/fswatcher_test.go
  internal/storage/v1/elasticsearch/factory.go
Labels: changelog:refactoring

#6912 Move pkg/telemetry to internal/telemetry
  cmd/all-in-one/main.go
  cmd/collector/app/server/grpc.go
  cmd/collector/app/server/http.go
  cmd/collector/app/span_processor.go
  cmd/collector/main.go
  cmd/ingester/main.go
  cmd/internal/flags/admin.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/jaeger/internal/extension/jaegerquery/server_test.go
  cmd/jaeger/internal/extension/jaegerstorage/extension.go
  cmd/query/app/server.go
  cmd/query/app/server_test.go
  cmd/query/app/token_propagation_test.go
  cmd/query/main.go
  cmd/remote-storage/app/server.go
  cmd/remote-storage/app/server_test.go
  cmd/remote-storage/main.go
  internal/storage/integration/remote_memory_storage.go
  internal/storage/metricstore/disabled/factory.go
  internal/storage/metricstore/disabled/factory_test.go
  internal/storage/metricstore/factory.go
  internal/storage/metricstore/factory_test.go
  internal/storage/metricstore/prometheus/factory.go
  internal/storage/metricstore/prometheus/factory_test.go
  internal/storage/v1/factory.go
  internal/storage/v1/grpc/factory.go
  internal/storage/v1/grpc/factory_test.go
  internal/storage/v1/mocks/MetricStoreFactory.go
  internal/telemetry/settings.go
  internal/telemetry/settings_test.go
Labels: changelog:refactoring

#6902 Remove pkg/discovery
  pkg/discovery/discoverer.go
  pkg/discovery/discoverer_test.go
  pkg/discovery/grpcresolver/grpc_resolver.go
  pkg/discovery/grpcresolver/grpc_resolver_test.go
  pkg/discovery/notifier.go
  pkg/discovery/notifier_test.go
  pkg/discovery/package_test.go
Labels: changelog:skip

#6907 Move pkg/jtracer to internal/jtracer
  cmd/all-in-one/main.go
  cmd/jaeger/internal/extension/jaegerquery/server.go
  cmd/query/app/apiv3/http_gateway_test.go
  cmd/query/app/grpc_handler.go
  cmd/query/app/grpc_handler_test.go
  cmd/query/app/http_handler.go
  cmd/query/app/http_handler_test.go
  cmd/query/app/server_test.go
  cmd/query/main.go
  internal/jtracer/jtracer.go
  internal/jtracer/jtracer_test.go
  internal/storage/v1/cassandra/savetracetest/main.go
Labels: changelog:refactoring

#6897 Move pkg/gzipfs to internal/gzipfs
  cmd/query/app/ui/assets.go
  internal/gzipfs/gzip.go
  internal/gzipfs/gzip_test.go
  internal/gzipfs/testdata/foobar
  internal/gzipfs/testdata/foobar.gz
  internal/gzipfs/testdata/foobaz.gz
  internal/gzipfs/testdata/foobaz_truncated.gz
  internal/gzipfs/testdata/not_archive.gz
Labels: changelog:refactoring

#6915 Remove model/prototest
  model/proto/model_test.proto
  model/prototest/model_test.pb.go
Labels: changelog:skip

#6917 Move model/converter to internal/converter
  cmd/anonymizer/app/anonymizer/anonymizer.go
  cmd/collector/app/handler/thrift_span_handler.go
  cmd/query/app/http_handler.go
  crossdock/services/agent.go
  crossdock/services/agent_test.go
  internal/converter/doc.go
  internal/converter/empty_test.go
  internal/converter/json/doc.go
  internal/converter/json/fixtures/domain_01.json
  internal/converter/json/fixtures/domain_es_01.json
  internal/converter/json/fixtures/es_01.json
  internal/converter/json/fixtures/ui_01.json
  internal/converter/json/from_domain.go
  internal/converter/json/from_domain_test.go
  internal/converter/json/json_span_compare_test.go
  internal/converter/json/package_test.go
  internal/converter/json/process_hashtable.go
  internal/converter/json/process_hashtable_test.go
  internal/converter/json/sampling.go
  internal/converter/json/sampling_test.go
  internal/converter/thrift/doc.go
  internal/converter/thrift/empty_test.go
  internal/converter/thrift/jaeger/doc.go
  internal/converter/thrift/jaeger/fixtures/domain_01.json
  internal/converter/thrift/jaeger/fixtures/domain_02.json
  internal/converter/thrift/jaeger/fixtures/domain_03.json
  internal/converter/thrift/jaeger/fixtures/thrift_batch_01.json
  internal/converter/thrift/jaeger/fixtures/thrift_batch_02.json
  internal/converter/thrift/jaeger/from_domain.go
  internal/converter/thrift/jaeger/from_domain_test.go
  internal/converter/thrift/jaeger/package_test.go
  internal/converter/thrift/jaeger/sampling_from_domain.go
  internal/converter/thrift/jaeger/sampling_from_domain_test.go
  internal/converter/thrift/jaeger/sampling_to_domain.go
  internal/converter/thrift/jaeger/sampling_to_domain_test.go
  internal/converter/thrift/jaeger/to_domain.go
  internal/converter/thrift/jaeger/to_domain_test.go
  internal/sampling/http/handler.go
  internal/sampling/http/handler_test.go
  pkg/gogocodec/codec_test.go
Labels: changelog:refactoring

#6913 Move pkg/version to internal/version
  cmd/all-in-one/main.go
  cmd/anonymizer/main.go
  cmd/collector/main.go
  cmd/esmapping-generator/main.go
  cmd/ingester/main.go
  cmd/internal/flags/admin.go
  cmd/jaeger/internal/command.go
  cmd/jaeger/main.go
  cmd/query/app/static_handler.go
  cmd/query/main.go
  cmd/remote-storage/main.go
  cmd/tracegen/main.go
  internal/version/build.go
  internal/version/build_test.go
  internal/version/command.go
  internal/version/command_test.go
  internal/version/handler.go
  internal/version/handler_test.go
  internal/version/package_test.go
Labels: changelog:refactoring

#6919 [grpc][v2] Implement v2 gRPC trace writer
  internal/storage/v2/grpc/tracewriter.go
  internal/storage/v2/grpc/tracewriter_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6918 Move model/proto to internal/proto
  cmd/query/app/query_parser.go
  docker-compose/monitor/README.md
  internal/proto/metrics/README.md
  internal/proto/metrics/openmetrics.proto
  internal/proto/metrics/otelspankind.proto
  scripts/makefiles/Protobuf.mk
Labels: changelog:refactoring

#6911 Move pkg/prometheus to internal/config/promcfg
  cmd/jaeger/internal/extension/jaegerstorage/config.go
  cmd/jaeger/internal/extension/jaegerstorage/extension_test.go
  internal/config/promcfg/config.go
  internal/config/promcfg/config_test.go
  internal/storage/metricstore/prometheus/factory.go
  internal/storage/metricstore/prometheus/factory_test.go
  internal/storage/metricstore/prometheus/metricstore/reader.go
  internal/storage/metricstore/prometheus/metricstore/reader_test.go
  internal/storage/metricstore/prometheus/options.go
Labels: changelog:refactoring

#6908 Move pkg/kafka to internal/kafka
  cmd/ingester/app/builder/builder.go
  cmd/ingester/app/consumer/consumer.go
  cmd/ingester/app/consumer/consumer_test.go
  cmd/ingester/app/consumer/processor_factory.go
  cmd/ingester/app/consumer/processor_factory_test.go
  cmd/ingester/app/flags.go
  cmd/ingester/app/flags_test.go
  internal/storage/integration/kafka_test.go
  internal/storage/kafka/auth/config.go
  internal/storage/kafka/auth/config_test.go
  internal/storage/kafka/auth/empty_test.go
  internal/storage/kafka/auth/kerberos.go
  internal/storage/kafka/auth/kerberos_test.go
  internal/storage/kafka/auth/options.go
  internal/storage/kafka/auth/options_test.go
  internal/storage/kafka/auth/plaintext.go
  internal/storage/kafka/auth/plaintext_test.go
  internal/storage/kafka/auth/tls.go
  internal/storage/kafka/auth/tls_test.go
  internal/storage/kafka/consumer/config.go
  internal/storage/kafka/consumer/config_test.go
  internal/storage/kafka/consumer/empty_test.go
  internal/storage/kafka/consumer/mocks/Consumer.go
  internal/storage/kafka/producer/config.go
  internal/storage/kafka/producer/config_test.go
  internal/storage/kafka/producer/empty_test.go
  internal/storage/v1/kafka/factory.go
  internal/storage/v1/kafka/factory_test.go
  internal/storage/v1/kafka/options.go
  internal/storage/v1/kafka/options_test.go
Labels: storage/kafka, changelog:refactoring

#6896 Move pkg/{gogocodec,httpfs,bearertoken,boundqueue} to internal
  cmd/collector/app/queue/bounded_queue.go
  cmd/collector/app/queue/bounded_queue_test.go
  cmd/collector/app/span_processor.go
  cmd/query/app/apiv3/gateway_test.go
  cmd/query/app/apiv3/grpc_handler_test.go
  cmd/query/app/grpc_handler.go
  cmd/query/app/server.go
  cmd/query/app/token_propagation_test.go
  cmd/query/app/ui/assets.go
  cmd/query/main.go
  cmd/remote-storage/app/server.go
  examples/hotrod/services/frontend/server.go
  internal/bearertoken/context.go
  internal/bearertoken/context_test.go
  internal/bearertoken/grpc.go
  internal/bearertoken/grpc_test.go
  internal/bearertoken/http.go
  internal/bearertoken/http_test.go
  internal/bearertoken/package_test.go
  internal/bearertoken/transport.go
  internal/bearertoken/transport_test.go
  internal/gogocodec/codec.go
  internal/gogocodec/codec_test.go
  internal/httpfs/prefixed.go
  internal/httpfs/prefixed_test.go
  internal/httpfs/test_assets/somefile.txt
  internal/jptrace/traces.go
  internal/storage/metricstore/prometheus/metricstore/reader.go
  internal/storage/metricstore/prometheus/metricstore/reader_test.go
  internal/storage/v1/elasticsearch/options.go
  internal/storage/v1/grpc/factory.go
  internal/storage/v1/grpc/shared/grpc_client.go
  internal/storage/v1/grpc/shared/grpc_handler.go
  pkg/es/config/config.go
Labels: changelog:refactoring

#6923 [ES][v2] Copy Jaeger<->OTLP translator from OTEL Contrib
  internal/storage/v2/elasticsearch/tracestore/from_dbmodel.go
  internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go
  internal/storage/v2/elasticsearch/tracestore/package_test.go
  internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go
  internal/storage/v2/elasticsearch/tracestore/to_dbmodel_test.go
Labels: area/storage, storage/elasticsearch, v2, changelog:exprimental

#6905 Move pkg/httpmetrics to internal/httpmetrics
  cmd/collector/app/server/http.go
  cmd/collector/app/server/httpmetrics/metrics.go
  cmd/collector/app/server/httpmetrics/metrics_test.go
Labels: changelog:refactoring

#6903 Move pkg/distributedlock to internal/distributedlock
  internal/distributedlock/empty_test.go
  internal/distributedlock/interface.go
  internal/distributedlock/mocks/Lock.go
  internal/leaderelection/leader_election.go
  internal/leaderelection/leader_election_test.go
  internal/sampling/samplingstrategy/adaptive/factory.go
  internal/sampling/samplingstrategy/adaptive/factory_test.go
  internal/sampling/samplingstrategy/metafactory/factory_test.go
  internal/storage/v1/badger/factory.go
  internal/storage/v1/cassandra/factory.go
  internal/storage/v1/factory.go
  internal/storage/v1/memory/factory.go
  internal/storage/v1/mocks/SamplingStoreFactory.go
Labels: changelog:refactoring

#6933 [grpc][v2] Implement v2 gRPC dependency reader
  internal/storage/v2/grpc/depreader.go
  internal/storage/v2/grpc/depreader_test.go
  internal/storage/v2/grpc/tracereader_test.go
Labels: area/storage, changelog:bugfix-or-minor-feature, v2

#6934 [ES][v2] Refactor `from_dbmodel` and `to_dbmodel` to accept and return DB Spans
  internal/storage/v2/elasticsearch/tracestore/from_dbmodel.go
  internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go
  internal/storage/v2/elasticsearch/tracestore/ids.go
  internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go
  internal/storage/v2/elasticsearch/tracestore/to_dbmodel_test.go
Labels: area/storage, v2, changelog:exprimental

#6942 [ES] Remove pointer signatures from `FromDBModel` and `ToDBModel`
  internal/storage/v2/elasticsearch/tracestore/from_dbmodel.go
  internal/storage/v2/elasticsearch/tracestore/from_dbmodel_test.go
  internal/storage/v2/elasticsearch/tracestore/to_dbmodel.go
  internal/storage/v2/elasticsearch/tracestore/to_dbmodel_test.go
Labels: storage/elasticsearch, changelog:refactoring
